from enum import Enum
from typing import Literal


class SemanticModelFormat(Enum):
    TMDL = "definition"
    LEGACY = "model.bim"


SourceType = Literal["calculated", "calculationGroup", "entity", "m"]

"""Supported partition modes
See: https://docs.tabulareditor.com/en/api/TabularEditor.TOMWrapper.ModeType.html"""
PartitionMode = Literal[
    "default",
    "directLake",
    "directQuery",
    "dual",
    "import",
    "push",
]

"""Supported data types
See: https://learn.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.datatype?view=analysisservices-dotnet"""
DataType = Literal[
    "binary",
    "boolean",
    "dateTime",
    "decimal",
    "double",
    "int64",
    "string",
    "unknown",
    "variant",
]

"""Supported data categories
The values in the following enumeration PropertyType are automatically mapped to the LEVEL_TYPE column that is defined in [MS-SSAS] section 3.1.4.2.2.1.3.8.1.

All other strings map to ExtendedType (248) and are returned as-is in the Contents property of conceptual schema definition language (CSDL) for the column:
See: https://learn.microsoft.com/en-us/openspecs/sql_server_protocols/ms-ssas-t/00a9ec7a-5f4d-4517-8091-b370fe2dc18b"""
DataCategory = Literal[
    "Latitude",  # not documented
    "Longitude",  # not documented
    "PaddedDateTableDates",  # not documented
    "Invalid",
    "All",
    "Regular",
    "Image",
    "ImageBMP",
    "ImageGIF",
    "ImageJPG",
    "ImagePNG",
    "ImageTIFF",
    "ImageUrl",  # alternative casing
    "ImageURL",
    "Id",
    "RelationToParent",
    "Sequence",
    "OrgTitle",
    "Caption",
    "ShortCaption",
    "CaptionDescription",
    "CaptionAbbreviation",
    "WebURL",
    "WebHTML",
    "WebXMLOrXSL",
    "WebmailAlias",
    "Address",
    "AddressStreet",
    "AddressHouse",
    "AddressCity",
    "AddressStateOrProvince",
    "AddressZIP",
    "AddressQuarter",
    "AddressCountry",
    "AddressBuilding",
    "AddressRoom",
    "AddressFloor",
    "AddressFax",
    "AddressPhone",
    "GeoCentroidX",
    "GeoCentroidY",
    "GeoCentroidZ",
    "GeoBoundaryTop",
    "GeoBoundaryLeft",
    "GeoBoundaryBottom",
    "GeoBoundaryRight",
    "GeoBoundaryFront",
    "GeoBoundaryRear",
    "GeoBoundaryPolygon",
    "PhysicalSize",
    "PhysicalColor",
    "PhysicalWeight",
    "PhysicalHeight",
    "PhysicalWidth",
    "PhysicalDepth",
    "PhysicalVolume",
    "PhysicalDensity",
    "PersonFullName",
    "PersonFirstName",
    "PersonLastName",
    "PersonMiddleName",
    "PersonDemographic",
    "PersonContact",
    "QtyRangeLow",
    "QtyRangeHigh",
    "FormattingColor",
    "FormattingOrder",
    "FormattingFont",
    "FormattingFontEffects",
    "FormattingFontSize",
    "FormattingSubtotal",
    "Date",
    "DateStart",
    "DateEnded",
    "DateCanceled",
    "DateModified",
    "DateDuration",
    "Version",
    "Years",
    "Quarters",
    "Months",
    "Weeks",
    "Days",
    "Hours",
    "Minutes",
    "Seconds",
    "UndefinedTime",
    "Time",  # not documented
    "OrganizationalUnit",
    "BomResource",
    "Quantitative",
    "Account",
    "Customers",
    "CustomerGroup",
    "CustomerHousehold",
    "Product",
    "ProductGroup",
    "Scenario",
    "Utility",
    "Person",
    "Company",
    "CurrencySource",
    "CurrencyDestination",
    "Channel",
    "Representative",
    "Promotion",
    "Continent",
    "Region",
    "Country",
    "StateOrProvince",
    "County",
    "City",
    "PostalCode",
    "Point",
    "AccountType",
    "AccountName",
    "AccountNumber",
    "ProjectName",
    "ProjectCode",
    "ProjectStartDate",
    "ProjectEndDate",
    "ProjectCompletion",
    "CurrencyName",
    "CurrencyIsOCode",
    "PercentOwnership",
    "PercentVoteright",
    "Project",
    "RateType",
    "Rate",
    "ProductSKU",
    "ProductCategory",
    "ProductBrand",
    "DeletedFlag",
    "ScdStatus",
    "ScdEndDate",
    "ScdOriginalID",
    "ScdStartDate",
    "DayOfMonthOrPeriod",
    "WeekOfQuarter",
    "WeekOfMonthOrPeriod",
    "MonthOrPeriodOfQuarter",
    "MonthOrPeriodOfYear",
    "Trimesters",
    "Halfyears",
    "Tendays",
    "DayOfWeek",
    "DayOfTendays",
    "DayOfMonth",
    "DayOfQuarter",
    "DayOfTrimester",
    "DayOfHalfyear",
    "DayOfYear",
    "WeekOfYear",
    "TendayOfMonth",
    "TendayOfQuarter",
    "TendayOfTrimester",
    "TendayOfHalfyear",
    "TendayOfYear",
    "MonthOfTrimester",
    "MonthOfQuarter",
    "MonthOfHalfyear",
    "MonthOfYear",
    "TrimesterOfYear",
    "QuarterOfHalfyear",
    "QuarterOfYear",
    "HalfyearOfYear",
    "FiscalDate",
    "FiscalDayOfWeek",
    "FiscalDayOfMonth",
    "FiscalDayOfQuarter",
    "FiscalDayOfTrimester",
    "FiscalDayOfHalfyear",
    "FiscalDayOfYear",
    "FiscalWeeks",
    "FiscalWeekOfYear",
    "FiscalWeekOfHalfyear",
    "FiscalWeekOfQuarter",
    "FiscalWeekOfTrimester",
    "FiscalWeekOfMonth",
    "FiscalMonths",
    "FiscalMonthOfTrimester",
    "FiscalMonthOfQuarter",
    "FiscalMonthOfHalfyear",
    "FiscalMonthOfYear",
    "FiscalTrimesters",
    "FiscalTrimesterOfYear",
    "FiscalQuarters",
    "FiscalQuarterOfYear",
    "FiscalQuarterOfHalfyear",
    "FiscalHalfyears",
    "FiscalHalfyearOfYear",
    "FiscalYears",
    "ReportingDate",
    "ReportingDayOfWeek",
    "ReportingDayOfMonth",
    "ReportingDayOfQuarter",
    "ReportingDayOfTrimester",
    "ReportingDayOfHalfyear",
    "ReportingDayOfYear",
    "ReportingWeeks",
    "ReportingWeekOfYear",
    "ReportingWeekOfHalfyear",
    "ReportingWeekOfQuarter",
    "ReportingWeekOfTrimester",
    "ReportingWeekOfMonth",
    "ReportingMonths",
    "ReportingMonthOfTrimester",
    "ReportingMonthOfQuarter",
    "ReportingMonthOfHalfyear",
    "ReportingMonthOfYear",
    "ReportingTrimesters",
    "ReportingTrimesterOfYear",
    "ReportingQuarters",
    "ReportingQuarterOfYear",
    "ReportingQuarterOfHalfyear",
    "ReportingHalfyears",
    "ReportingHalfyearOfYear",
    "ReportingYears",
    "ManufacturingDate",
    "ManufacturingDayOfWeek",
    "ManufacturingDayOfMonth",
    "ManufacturingDayOfQuarter",
    "ManufacturingDayOfHalfyear",
    "ManufacturingDayOfYear",
    "ManufacturingWeeks",
    "ManufacturingWeekOfYear",
    "ManufacturingWeekOfHalfyear",
    "ManufacturingWeekOfQuarter",
    "ManufacturingWeekOfMonth",
    "ManufacturingMonths",
    "ManufacturingMonthOfQuarter",
    "ManufacturingMonthOfHalfyear",
    "ManufacturingMonthOfYear",
    "ManufacturingTrimesters",
    "ManufacturingTrimesterOfYear",
    "ManufacturingQuarters",
    "ManufacturingQuarterOfYear",
    "ManufacturingQuarterOfHalfyear",
    "ManufacturingHalfyears",
    "ManufacturingHalfyearOfYear",
    "ManufacturingYears",
    "WinterSummerSeason",
    "IsHoliday",
    "IsWeekday",
    "IsWorkingDay",
    "IsPeakDay",
    "ISO8601Date",
    "ISO8601DayOfWeek",
    "ISO8601DayOfYear",
    "ISO8601Weeks",
    "ISO8601WeekOfYear",
    "ISO8601Years",
    "RowNumber",
    "ExtendedType",
]


ColumnType = Literal["calculated", "calculatedTableColumn"]

Alignment = Literal["default", "left", "right", "center"]

"""
See: https://learn.microsoft.com/en-us/openspecs/sql_server_protocols/ms-ssas-t/00a9ec7a-5f4d-4517-8091-b370fe2dc18b
See: https://docs.tabulareditor.com/en/api/TabularEditor.TOMWrapper.Column.html#TabularEditor_TOMWrapper_Column_SummarizeBy
"""
SummarizeBy = Literal[
    "default",
    "none",
    "sum",
    "min",
    "max",
    "count",
    "average",
    "distinctCount",
]
