[project]
name = "pybi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Willian Hayashida", email = "will.hayashida07@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.12.5",
]

[build-system]
requires = ["uv_build>=0.9.14,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "datamodel-code-generator>=0.55.0",
    "pytest>=9.0.2",
]


[tool.pytest.ini_options]
markers = [
    "perf: performance benchmark tests",
    "benchmark: benchmark-grouped tests for codspeed/pytest-benchmark",
]
