# generated by datamodel-codegen:
#   filename:  schema.json


from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class PagesMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pageOrder: list[str] | None = Field(None,
        description="Defines the order in which report pages are rendered (page names). If omitted, they will be ordered by display name by default.\nIf there are pages in this list, that don't have a corresponding definition, they will be ignored.\nPages with definitions, but not in this list will be ordered by display name and appended to the end, after pages that exist in this list.",
    )
    activePageName: str | None = Field(None,
        description='Report will open on this page by default - if omitted, report will open on first page based on order defined by pageOrder semantics.',
    )
    field_schema: Literal[
        'https://developer.microsoft.com/json-schemas/fabric/item/report/definition/pagesMetadata/1.0.0/schema.json'
    ] = Field(
        ..., alias='$schema', description='Defines the schema to use for an item.'
    )
