# generated by datamodel-codegen:
#   filename:  schema.json



from pydantic import BaseModel, ConfigDict, Field

# --- Imports from dependency schemas (auto-generated) ---

# --- Imports from dependency schemas (auto-generated) ---



class QueryCustomTotalMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseQueryName: str = Field(
        ...,
        description='The query name of the base column that this custom total references. This establishes the relationship between a custom total and the column it refers to.',
    )


class Annotations(BaseModel):
    customTotalMetadata: QueryCustomTotalMetadata | None= None


