# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class PrimitiveTypeName(Enum):
    Binary = 'Binary'
    Boolean = 'Boolean'
    Date = 'Date'
    DateTime = 'DateTime'
    DateTimeZone = 'DateTimeZone'
    Decimal = 'Decimal'
    Double = 'Double'
    Duration = 'Duration'
    Integer = 'Integer'
    Json = 'Json'
    None_ = 'None'
    Null = 'Null'
    Text = 'Text'
    Time = 'Time'
    Variant = 'Variant'


class ReportExtensionMeasureTemplate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    daxTemplateName: str = Field(..., description='Name of the template.')
    version: float = Field(..., description='Version of the template used.')


class MeasureExtensionAnnotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Unique name for this annotation.')
    value: str = Field(..., description='Value for the annotation.')


class MeasureReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_: str | None = Field(None,
        alias='schema',
        description='Name of the schema - leave empty if using model measures. Use name of extension if using other measures from the extension.',
    )
    entity: str = Field(..., description='Entity name of the measure.')
    name: str = Field(..., description='Name of the measure.')


class ExpressionReferences(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    unrecognizedReferences: bool | None = Field(None, description='False if all references are recognized.'
    )
    measures: list[MeasureReference] | None = Field(None, description='References to model measures and other extensions.'
    )


class ReportExtensionMeasure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ...,
        description='Name of the extension measure - must be unique across the semantic model and other extension measures.',
    )
    dataType: PrimitiveTypeName = Field(..., description='Data type for the measure.')
    dataCategory: str | None = Field(None, description='Extended data category for the measure.'
    )
    expression: str = Field(..., description='DAX expression for this measure.')
    hidden: bool | None = Field(None, description='Sets the measure to be hidden.')
    formatString: str | None = Field(None, description='Format string for this measure in VBA format.'
    )
    measureTemplate: ReportExtensionMeasureTemplate | None = Field(None, description='Template information that was used to create this measure.'
    )
    description: str | None = Field(None, description='A description for the measure.')
    displayFolder: str | None = Field(None, description='Display folder for the measure.'
    )
    annotations: list[MeasureExtensionAnnotation] | None = Field(None, description='Additional annotations to include for this measure.'
    )
    references: ExpressionReferences | None = Field(None,
        description='References to other model measures and extensions used in the DAX of this measure.',
    )


class ReportExtensionEntity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ...,
        description='Name of the extension entity - must match a name in the semantic model.',
    )
    measures: list[ReportExtensionMeasure] | None = Field(None, description='Additional measures to include on this entity.'
    )


class ReportExtension(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the extension.')
    entities: list[ReportExtensionEntity] | None = Field(None, description='Entities in the semantic model that are extended.'
    )
    field_schema: Literal[
        'https://developer.microsoft.com/json-schemas/fabric/item/report/definition/reportExtension/1.0.0/schema.json'
    ] = Field(
        ..., alias='$schema', description='Defines the schema to use for an item.'
    )
