table COVID
	lineageTag: a755fb70-618a-4549-98cd-b83e7f602006

	measure Updated = "Data provided by USAFacts. Because of the frequency of data upates, they may not reflect the exact numbers reported by government organizations or the news media. For more information or to download the data, please click the logo below.  Data updated through " & FORMAT([Max date],"mmmm dd, yyyy") & "."
		lineageTag: ecd7259c-c19b-4a27-a726-844b3356d8fd

	measure 'Max date' = CALCULATE(MAX('COVID'[Date]),ALL('COVID'))
		formatString: General Date
		isHidden
		lineageTag: 91921841-1a89-445e-913c-f510c38840b7

	column 'County Name'
		dataType: string
		lineageTag: 73278cdd-5af8-4327-a50b-317152db0a12
		summarizeBy: none
		sourceColumn: County Name

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: bce04757-7746-45d2-acca-ac1bcf0a6ce0
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: m/d/yyyy
		lineageTag: c3f13aae-9287-4bde-84f9-7791ff2b462e
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 61d3981d-89bc-4f78-b2b7-ab908a42ac71
			defaultHierarchy: LocalDateTable_a0f5b894-4f57-4a54-a9d5-5508aa5843d0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Cases
		dataType: int64
		formatString: 0
		lineageTag: 93f352da-e476-4d57-88b1-386d35ee539c
		summarizeBy: sum
		sourceColumn: Cases

		annotation SummarizationSetBy = Automatic

	column FIPS
		dataType: string
		lineageTag: a0a505be-6fdb-4b95-8895-a06c68778f69
		summarizeBy: none
		sourceColumn: FIPS

		annotation SummarizationSetBy = Automatic

	column Deaths
		dataType: int64
		formatString: 0
		lineageTag: 584bc905-5c4e-4d28-a441-379b5a8a985d
		summarizeBy: sum
		sourceColumn: Deaths

		annotation SummarizationSetBy = Automatic

	column County = 'COVID'[County Name] & ", " & 'COVID'[State]
		lineageTag: 35e04fd9-50d7-4b81-8c21-8ac5bf177a69
		dataCategory: County
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Daily cases' = ```
			
			VAR __CountyName = 'COVID'[County Name]
			VAR __State = 'COVID'[State]
			VAR __Yesterday =  DATEADD(COVID[Date],-1,DAY)
			VAR __TodaysCases = 'COVID'[Cases]
			
			RETURN  __TodaysCases - CALCULATE(
			    SUM('COVID'[Cases]) , 
			    FILTER(
			        COVID, 
			        COVID[Date] = __Yesterday &&
			        COVID[County Name] = __CountyName &&
			        COVID[State] = __State
			    )
			) + 0
			```
		formatString: #,0
		lineageTag: 3c76fd35-d104-4568-a162-a19dd8b49769
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Daily deaths' = ```
			
			VAR __CountyName = 'COVID'[County Name]
			VAR __State = 'COVID'[State]
			VAR __Yesterday =  DATEADD(COVID[Date],-1,DAY)
			VAR __TodaysDeaths = 'COVID'[Deaths]
			
			RETURN  __TodaysDeaths - CALCULATE(
			    SUM('COVID'[Deaths]) , 
			    FILTER(
			        COVID, 
			        COVID[Date] = __Yesterday &&
			        COVID[County Name] = __CountyName &&
			        COVID[State] = __State
			    )
			) + 0
			```
		formatString: 0
		lineageTag: c1c4daa6-19fb-4cf0-86b0-294c7c800f02
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column StateFIPS
		dataType: string
		lineageTag: d08434c4-91de-4bdd-b824-718920a19dbf
		summarizeBy: none
		sourceColumn: StateFIPS

		annotation SummarizationSetBy = Automatic

	partition COVID-2e509512-c6a9-426c-b8d3-3b5c4542fa79 = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(Cases, {"County Name", "State", "StateFIPS", "Date", "FIPS"}, Deaths, {"County Name", "State", "StateFIPS", "Date", "FIPS"}, "Deaths", JoinKind.LeftOuter),
				    #"Expanded Deaths" = Table.ExpandTableColumn(Source, "Deaths", {"Deaths"}, {"Deaths.1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Deaths",{{"Deaths.1", "Deaths"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Jackson County (including other portions of Kansas City)","Jackson County",Replacer.ReplaceText,{"County Name"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","New York City","New York*",Replacer.ReplaceText,{"County Name"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","City of St. Louis","St. Louis City",Replacer.ReplaceText,{"County Name"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","City and Borough of Juneau","Juneau Borough",Replacer.ReplaceText,{"County Name"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Municipality of Anchorage","Anchorage",Replacer.ReplaceText,{"County Name"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value4",{{"Cases", Int64.Type}, {"Deaths", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

