# generated by datamodel-codegen:
#   filename:  schema-embedded.json


from typing import Any, Literal, Annotated

from pydantic import BaseModel, ConfigDict, Field, StringConstraints
from ...semanticquery.expressions import QueryExpressionContainer
from ...formattingobjectdefinitions.v1_3_0.model import DataViewWildcard, HierarchyMatching, HighlightMatching
from ...semanticquery.v1_4_0.model import QueryCustomTotalMetadata
from ...visualconfiguration.v2_2_0.model import AIDecompositionMethod, SortDirectionModel


class VisualQueryOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowBinnedLineSample: bool | None= Field(None, description='A better sampling for line charts.'
    )
    allowOverlappingPointsSample: bool | None= Field(None, description='A better sampling for scatter charts.'
    )


class Title(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None= None
    text: Any | None= None
    heading: Any | None= None
    titleWrap: Any | None= None
    fontColor: Any | None= None
    background: Any | None= None
    alignment: Any | None= None
    fontSize: Any | None= None
    bold: Any | None= None
    italic: Any | None= None
    underline: Any | None= None
    fontFamily: Any | None= None


class SubTitle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None= None
    text: Any | None= None
    heading: Any | None= None
    titleWrap: Any | None= None
    fontColor: Any | None= None
    alignment: Any | None= None
    fontSize: Any | None= None
    bold: Any | None= None
    italic: Any | None= None
    underline: Any | None= None
    fontFamily: Any | None= None


class Divider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ignorePadding: Any | None= None
    show: Any | None= None
    color: Any | None= None
    width: Any | None= None
    style: Any | None= None


class Spacing(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    customizeSpacing: Any | None= None
    verticalSpacing: Any | None= None
    spaceBelowTitle: Any | None= None
    spaceBelowSubTitle: Any | None= None
    spaceBelowTitleArea: Any | None= None


class Background(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None= None
    color: Any | None= None
    transparency: Any | None= None


class Padding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    top: Any | None= None
    bottom: Any | None= None
    left: Any | None= None
    right: Any | None= None


class LockAspect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None= None


class VisualContainerGeneralFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: Any | None= None
    y: Any | None= None
    width: Any | None= None
    height: Any | None= None
    altText: Any | None= None
    allowBinnedLineSample: Any | None= None
    allowOverlappingPointsSample: Any | None= None
    keepLayerOrder: Any | None= None


class Border(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None= None
    color: Any | None= None
    radius: Any | None= None
    width: Any | None= None


class DropShadow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None= None
    preset: Any | None= None
    position: Any | None= None
    color: Any | None= None
    transparency: Any | None= None
    shadowSpread: Any | None= None
    shadowBlur: Any | None= None
    angle: Any | None= None
    shadowDistance: Any | None= None


class VisualLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None= None
    type: Any | None= None
    bookmark: Any | None= None
    disabledTooltip: Any | None= None
    drillthroughSection: Any | None= None
    enabledTooltip: Any | None= None
    qna: Any | None= None
    suppressDefaultTooltip: Any | None= None
    showDefaultTooltip: Any | None= None
    navigationSection: Any | None= None
    tooltip: Any | None= None
    tooltipPlaceholderText: Any | None= None
    webUrl: Any | None= None
    dataFunction: Any | None= None


class VisualTooltip(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None= None
    type: Any | None= None
    section: Any | None= None
    titleFontColor: Any | None= None
    valueFontColor: Any | None= None
    fontSize: Any | None= None
    bold: Any | None= None
    italic: Any | None= None
    underline: Any | None= None
    fontFamily: Any | None= None
    background: Any | None= None
    transparency: Any | None= None
    actionFontColor: Any | None= None
    themedTitleFontColor: Any | None= None
    themedBackground: Any | None= None
    themedValueFontColor: Any | None= None


class StylePreset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Any | None= None


class VisualHeader(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None= None
    background: Any | None= None
    border: Any | None= None
    transparency: Any | None= None
    foreground: Any | None= None
    showVisualInformationButton: Any | None= None
    showVisualWarningButton: Any | None= None
    showVisualErrorButton: Any | None= None
    showDrillRoleSelector: Any | None= None
    showDrillUpButton: Any | None= None
    showDrillToggleButton: Any | None= None
    showDrillDownLevelButton: Any | None= None
    showDrillDownExpandButton: Any | None= None
    showPinButton: Any | None= None
    showFilterRestatementButton: Any | None= None
    showFocusModeButton: Any | None= None
    showCopyVisualImageButton: Any | None= None
    showSeeDataLayoutToggleButton: Any | None= None
    showOptionsMenu: Any | None= None
    showCommentButton: Any | None= None
    showTooltipButton: Any | None= None
    showPersonalizeVisualButton: Any | None= None
    showSmartNarrativeButton: Any | None= None
    showSetAlertButton: Any | None= None
    showFollowVisualButton: Any | None= None


class VisualHeaderTooltip(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Any | None= None
    section: Any | None= None
    text: Any | None= None
    titleFontColor: Any | None= None
    fontSize: Any | None= None
    fontFamily: Any | None= None
    bold: Any | None= None
    italic: Any | None= None
    underline: Any | None= None
    background: Any | None= None
    transparency: Any | None= None
    themedTitleFontColor: Any | None= None
    themedBackground: Any | None= None


class VisualSyncGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    groupName: str = Field(..., description='Unique name for the sync group.')
    fieldChanges: bool | None= Field(None, description='Should synced visuals update when fields change.'
    )
    filterChanges: bool | None= Field(None, description='Should synced visuals update when filters change.'
    )


class Annotations(BaseModel):
    customTotalMetadata: QueryCustomTotalMetadata | None= None


class AILevelInformation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: AIDecompositionMethod = Field(..., description='Type of expansion.')
    disabled: bool | None= Field(None, description='Is the level disabled.')


class VisualConfiguration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visualType: str = Field(..., description='Name of the visual.')
    autoSelectVisualType: bool | None= Field(None,
        description='VisualType is automatically picked by the system based on the data used in the visual.',
    )
    query: Query | None= Field(None, description='Defines the data to be plotted in the visual.'
    )
    expansionStates: list[ExpansionState] | None= Field(None, description='Defines the specific data points that are expanded.'
    )
    objects: dict[str, list[DataViewObjectDefinition]] | None= Field(None,
        description='Specifies the formatting to be set for different "objects" of the visual.',
    )
    visualContainerObjects: VisualContainerFormattingObjects | None= Field(None,
        description='Specifies the formatting to be set for different "objects" of the container.',
    )
    syncGroup: VisualSyncGroup | None= Field(None,
        description='Defines the sync group that this visual is part of.\nOnly applies to slicer visuals.',
    )
    drillFilterOtherVisuals: bool | None= Field(None,
        description='When another visual is drilled, if visual interactions are enabled between the two visuals,\nthen this property specifies if that drill should be applied as a filter to this visual.\nOverrides the default setting of the report.',
    )


class DataViewObjectDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= None
    properties: dict[str, Any]


class Selector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[DataRepetitionSelector] | None= Field(None, description='Scope is defined by data bound to the visual.'
    )
    metadata: str | None= Field(None, description='Defines the scope to a specific field.'
    )
    id: str | None= Field(None, description='User defined scope.')
    highlightMatching: HighlightMatching | None= Field(None,
        description='Describes how the Selector should behave towards Highlighted Values within the Scope matched by that Selector.',
    )
    hierarchyMatching: HierarchyMatching | None= Field(None,
        description='Describes how the selector matches hierarchy values.\nThis also changes how the query is generated for {@link DataViewScopeWildcard} selectors.\nNow those selectors can produce scopedValues for the level those match.\n\nThere are two ways that we can match values in the hierarchy:\n1.',
    )
    order: float | None= Field(None,
        description='Specifies a user-defined ordering of identical properties.\nSelector constructors should strive to monitonically increase this number across identical properties differing by id.',
    )


class DataRepetitionSelector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scopeId: QueryExpressionContainer | None= Field(None,
        description='Defines the intersection of scopes. For example - product color = red.',
    )
    wildcard: list[QueryExpressionContainer] | None= Field(None,
        description='Defines a match against all instances of a given DataView scope. Does not match Subtotals.\nDeprecated: - Use roles instead.',
    )
    roles: list[str] | None= Field(None, description='Matches against all fields in a role.'
    )
    total: list[QueryExpressionContainer] | None= Field(None, description='Matches against the totals and subtotals.')
    dataViewWildcard: DataViewWildcard | None= Field(None, description='Matches all instances or all totals or both.'
    )


class Query(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sortDefinition: SortDefinition | None= Field(None, description='Defines how the data should be sorted in a visual'
    )
    options: VisualQueryOptions | None= Field(None,
        description='Specific options to apply when running the query. Applies to certain visuals only.',
    )
    queryState: dict[str, ProjectionState] = Field(
        ...,
        description='Describes how the data should be arranged and used in the visual.',
    )
    isDrillDisabled: bool | None= Field(None,
        description='Should drill be allowed in the visual - only used by specific custom visuals.',
    )


class SortDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sort: list[QuerySort] | None= Field(None, description='Defines the fields the data is sorted by.'
    )
    isDefaultSort: bool | None= Field(None,
        description='If the sort if explicitly set by user, then this will be false, Power BI can update the sort to match\nthe visual in this case.',
    )


class QuerySort(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: QueryExpressionContainer = Field(..., description='Field to sort by')
    direction: SortDirectionModel = Field(
        ..., description='Direction of sort - ascending or descending.'
    )


class ProjectionState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    showAll: bool | None= Field(None, description='Show all values for all fields in this projection.'
    )
    projections: list[RoleProjection] = Field(
        ..., description='Defines the fields and their properties for this visual role.'
    )
    fieldParameters: list[RoleFieldParameter] | None= Field(None, description='Defines any field parameters used as projections.'
    )


class RoleProjection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: QueryExpressionContainer = Field(..., description='The data field from the semantic model.')
    queryRef: str = Field(
        ..., description='A unique name for this field - unique per visual.'
    )
    nativeQueryRef: str | None= Field(None,
        description='Native reference name for this field - unique per visual, used for referencing fields in visual calculations.',
    )
    displayName: str | None= Field(None,
        description='An override for display name - by default it is the field name in the semantic model.',
    )
    format: Annotated[str, StringConstraints(max_length=255)] | None = Field(None, description='format string scoped to the visual.'
    )
    active: bool | None= Field(None,
        description='Is the field currently active in the visual - used as part of drill operations.',
    )
    hidden: bool | None= Field(None,
        description='Is the field visible in the visual - used as part of visual calculations.',
    )


class RoleFieldParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    parameterExpr: QueryExpressionContainer = Field(
        ...,
        description='Defines the parameter field.\nThis contains the DAX expression (in semantic model) that defines what fields will be projected in the field well from the parameter.',
    )
    index: float = Field(
        ...,
        description="Index at which parameter fields begin in the projections list.\nThis represents the position in the field well where the field parameter is located.\nA field well can contain either projections or field parameters.\nWhen this index is changed, it affects where the field parameter's projected fields will be inserted\nin the projections list.",
    )
    length: float | None= Field(None,
        description="Number of projections that will be populated starting from the field parameter's index position.\nThis indicates how many fields the parameter will project into when evaluated.\n\nThis value will be re-computed when the parameter is evaluated, which is when the visual is rendered.",
    )
    sortDirection: SortDirectionModel | None= Field(None,
        description="If the sort direction is set, the visual is sorted by this field parameter.\nThe implication of a visual being sorted by a field parameter is as follows:\n- If none of the newly projected fields exist in the sort list, apply the parameter sort direction to the first projected field and add it to the end of the sort list.\n- If all the projected fields in the sort list have the opposite sort direction as the parameter's sort direction, flip the parameter's sort direction.",
    )


class ExpansionState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    roles: list[str] = Field(
        ...,
        description='Visual roles (projection names) that have individual points expanded.',
    )
    root: RootExpansionState | None= Field(None,
        description='Defines the specific values that are expanded for each field in the hierarchy',
    )
    levels: list[LevelExpansionState] | None= Field(None, description='Describes the fields participating in the expansion'
    )


class RootExpansionState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identityValues: list[QueryExpressionContainer] | None= Field(None,
        description='Describes the instances that are expanded.\nOptional for the root expansion state.\nMust by Literal expressions.',
    )
    isToggled: bool | None= Field(None, description='True if the value is expanded.')
    children: list[NodeExpansionState] | None= Field(None, description='Child values in the hierarchy that are expanded'
    )


class NodeExpansionState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identityValues: list[QueryExpressionContainer] = Field(
        ...,
        description='Describes the instances that are expanded.\nMust by Literal expressions.',
    )
    isToggled: bool | None= Field(None, description='True if the value is expanded.')
    children: list[NodeExpansionState] | None= Field(None, description='Child values in the hierarchy that are expanded'
    )


class LevelExpansionState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identityKeys: list[QueryExpressionContainer] | None= Field(None, description='Describes the fields in the visual.')
    isCollapsed: bool | None= Field(None,
        description="True if the entire field isn't expanded (i.e. false if only specific instances are expanded).",
    )
    queryRefs: list[str] = Field(
        ...,
        description='Which fields in the query does this relate to - must match a queryRef in the query.',
    )
    isPinned: bool | None= Field(None, description='Is the field pinned.')
    isLocked: bool | None= Field(None, description='Is the field locked (used for decomposition tree)'
    )
    AIInformation: AILevelInformation | None= Field(None,
        description='More information about how the expansion is done (used for decomposition tree)',
    )


class TitleItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: Title = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class SubTitleItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: SubTitle = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class DividerItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: Divider = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class SpacingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: Spacing = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class BackgroundItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: Background = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class PaddingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: Padding = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class LockAspectItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: LockAspect = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class GeneralItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: VisualContainerGeneralFormattingObjects = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class BorderItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: Border = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class DropShadowItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: DropShadow = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class VisualLinkItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: VisualLink = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class VisualTooltipItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: VisualTooltip = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class StylePresetItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: StylePreset = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class VisualHeaderItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: VisualHeader = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class VisualHeaderTooltipItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: VisualHeaderTooltip = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class VisualContainerFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: list[TitleItem] | None= None
    subTitle: list[SubTitleItem] | None= None
    divider: list[DividerItem] | None= None
    spacing: list[SpacingItem] | None= None
    background: list[BackgroundItem] | None= None
    padding: list[PaddingItem] | None= None
    lockAspect: list[LockAspectItem] | None= None
    general: list[GeneralItem] | None= None
    border: list[BorderItem] | None= None
    dropShadow: list[DropShadowItem] | None= None
    visualLink: list[VisualLinkItem] | None= None
    visualTooltip: list[VisualTooltipItem] | None= None
    stylePreset: list[StylePresetItem] | None= None
    visualHeader: list[VisualHeaderItem] | None= None
    visualHeaderTooltip: list[VisualHeaderTooltipItem] | None= None


VisualConfiguration.model_rebuild()
DataViewObjectDefinition.model_rebuild()
Selector.model_rebuild()
DataRepetitionSelector.model_rebuild()
Query.model_rebuild()
SortDefinition.model_rebuild()
ProjectionState.model_rebuild()
ExpansionState.model_rebuild()
RootExpansionState.model_rebuild()
NodeExpansionState.model_rebuild()
