table Month
	isHidden
	lineageTag: 39ade5a0-3c76-4b24-a645-524bfe398857

	column ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0476fade-d923-4474-87d4-44d8decd5d82
		summarizeBy: none
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		isHidden
		lineageTag: 35025433-53c8-4278-a48e-62630e993c0c
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Month-18692bd2-081e-439c-860a-48a4b29964ea = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlfSUfJKzCtNLKpUitWJVrIA8t1Sk4rgApZAAd/EouQMMM/QAMh1LCjKzIFwDcGyEJWGRiCzSvNSY/JAJEQMLJQDUQCSdyxNLy0uAXONgdzg1IKS1Nyk1CKwiAlQxD+5JB/GNwXy/fLLEArMgAIuqclQgVgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [ID = _t, Month = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Month", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","June#(lf)June","June",Replacer.ReplaceText,{"Month"})
				in
				    #"Replaced Value"

	annotation PBI_Id = c98ab75f-c83d-44a1-a4bf-4e032768be40

	annotation LinkedQueryName = Month

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

