# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Annotated

from pydantic import BaseModel, ConfigDict, Field, StringConstraints
from ...semanticquery.expressions import FilterDefinition, QueryExpressionContainer
from ...filterconfiguration.v1_1_0.model import FilterSortOrder, HowCreated, Type1
from ...formattingobjectdefinitions.v1_3_0.model import HierarchyMatching
from ...page.v1_4_0.model import Annotation


class ReportSource(Enum):
    Default = 'Default'
    SharePoint = 'SharePoint'
    Teams = 'Teams'
    QuickCreate = 'QuickCreate'
    EmbedQuickCreate = 'EmbedQuickCreate'
    Datamart = 'Datamart'
    DataExplore = 'DataExplore'


class Type(Enum):
    Categorical = 'Categorical'
    Range = 'Range'
    Advanced = 'Advanced'
    Passthrough = 'Passthrough'
    TopN = 'TopN'
    Include = 'Include'
    Exclude = 'Exclude'
    RelativeDate = 'RelativeDate'
    Tuple = 'Tuple'
    RelativeTime = 'RelativeTime'
    VisualTopN = 'VisualTopN'


class FilterContainerFormattingObjectsProperties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requireSingleSelect: Any | None= None
    isInvertedSelectionMode: Any | None= None


class ThemeVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visual: Annotated[str, StringConstraints(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$')] = Field(
        ..., description='The max visual container version at import.'
    )
    page: Annotated[str, StringConstraints(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$')] = Field(
        ..., description='The max page version at import.'
    )
    report: Annotated[str, StringConstraints(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$')] = Field(
        ..., description='The max report version at import.'
    )


class ThemeResourcePackageType(Enum):
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'


class OutspacePane(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expanded: Any | None= None
    visible: Any | None= None


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verticalAlignment: Any | None= None


class ResourcePackageType(Enum):
    CustomVisual = 'CustomVisual'
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'
    OrganizationalStoreCustomVisual = 'OrganizationalStoreCustomVisual'


class ResourcePackageItemType(Enum):
    CustomVisualJavascript = 'CustomVisualJavascript'
    CustomVisualsCss = 'CustomVisualsCss'
    CustomVisualScreenshot = 'CustomVisualScreenshot'
    CustomVisualIcon = 'CustomVisualIcon'
    CustomVisualWatermark = 'CustomVisualWatermark'
    CustomVisualMetadata = 'CustomVisualMetadata'
    Image = 'Image'
    ShapeMap = 'ShapeMap'
    CustomTheme = 'CustomTheme'
    BaseTheme = 'BaseTheme'
    DashboardTheme = 'DashboardTheme'
    DashboardBaseTheme = 'DashboardBaseTheme'
    HighContrastTheme = 'HighContrastTheme'
    AppNavigation = 'AppNavigation'
    AppTheme = 'AppTheme'
    AppBaseTheme = 'AppBaseTheme'


class OrganizationCustomVisual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the organization custom visual.')
    path: str = Field(..., description='Path where the custom visual is stored.')
    disabled: bool | None= Field(None,
        description='Signifies if the custom visual is disabled by the organization.',
    )


class ExportDataMode(Enum):
    AllowSummarized = 'AllowSummarized'
    AllowSummarizedAndUnderlying = 'AllowSummarizedAndUnderlying'
    None_ = 'None'


class PagesPosition(Enum):
    PagesPane = 'PagesPane'
    Bottom = 'Bottom'


class QueryLimitOption(Enum):
    None_ = 'None'
    Shared = 'Shared'
    Premium = 'Premium'
    SQLServerAS = 'SQLServerAS'
    AzureAS = 'AzureAS'
    Custom = 'Custom'
    Auto = 'Auto'


class FieldParameterReportSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    skipHierarchyLevelPersistence: bool | None= Field(None,
        description="If disabled, during parameter resolution, the hierarchy level and expand/collapse state of the visual won't be persisted",
    )


class ExplorationSlowDataSourceSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isCrossHighlightingDisabled: bool | None= Field(None, description='Disable cross highlights.'
    )
    isSlicerSelectionsButtonEnabled: bool | None= Field(None, description="Adds 'apply' button to slicers."
    )
    isFilterSelectionsButtonEnabled: bool | None= Field(None, description="Adds 'apply' button to filters."
    )
    isFieldWellButtonEnabled: bool | None= Field(None, description="Adds 'apply' button to field changes."
    )
    isApplyAllButtonEnabled: bool | None= Field(None, description='Adds an apply all button.'
    )


class DataViewWildcard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    matchingOption: Type1 = Field(
        ..., description='Defines the matching option to use.'
    )


class ThemeMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the theme.')
    reportVersionAtImport: ThemeVersion = Field(
        ..., description='Versions when the theme was added to the report.'
    )
    type: ThemeResourcePackageType = Field(
        ..., description='Built-in or user specific custom theme.'
    )


class ResourcePackageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None= None
    name: str
    path: str
    type: ResourcePackageItemType


class ExplorationSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isPersistentUserStateDisabled: bool | None= Field(None,
        description='Disable saving state of changes to a report as report viewers modify slicers and filters.',
    )
    hideVisualContainerHeader: bool | None= Field(None, description='Hide visual container header in view mode of the report.'
    )
    useStylableVisualContainerHeader: bool | None= Field(None, description='Use the new visual container header that is formattable.'
    )
    exportDataMode: ExportDataMode | None= Field(None, description='When exporting data, what should be exported.'
    )
    isReportAnnotationsDisabled: bool | None= Field(None, description='Commenting is disabled for this report.'
    )
    defaultFilterActionIsDataFilter: bool | None= Field(None,
        description='When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.',
    )
    defaultDrillFilterOtherVisuals: bool | None= Field(None,
        description='When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.',
    )
    useCrossReportDrillthrough: bool | None= Field(None, description='Allow drill-through from other reports to this report.'
    )
    allowChangeFilterTypes: bool | None= Field(None, description='Disables changing the type of filter in view mode.'
    )
    allowInlineExploration: bool | None= Field(None, description='Allows personalize this visual for the report in view mode.'
    )
    useEnhancedTooltips: bool | None= Field(None, description='Uses better tooltips for the visuals in this report.'
    )
    useScaledTooltips: bool | None= Field(None, description='If enabled, the tooltip will scale to match canvas zoom.'
    )
    filterPaneHiddenInEditMode: bool | None= Field(None, description='Hide the filter pane in view mode.'
    )
    disableFilterPaneSearch: bool | None= Field(None, description='Disables the search bar in filter pane.'
    )
    pagesPosition: PagesPosition | None= Field(None, description='Default location where the page navigator is shown.'
    )
    allowAutomatedInsightsNotification: bool | None= Field(None,
        description='Allow generating insights for the report in the background on data refresh.',
    )
    useDefaultAggregateDisplayName: bool | None= Field(None,
        description='Show the default aggregate in display names for summarized data.',
    )
    enableDeveloperMode: bool | None= Field(None, description='Enables developer mode for testing private custom visuals.'
    )
    pauseQueries: bool | None= Field(None,
        description="Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.",
    )
    queryLimitOption: QueryLimitOption | None= Field(None,
        description='Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits',
    )
    customMemoryLimit: str | None= Field(None,
        description='If custom query limit is applied, this value defines the memory limit.',
    )
    customTimeoutLimit: str | None= Field(None,
        description='If custom query limit is applied, this value defines the timeout limit.',
    )
    fieldParameterReportSettings: FieldParameterReportSettings | None= Field(None,
        description='Settings that will control the field parameter across all the visual in the report',
    )


class ThemeCollection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseTheme: ThemeMetadata | None= Field(None,
        description='Defines the base monthly release themes shipped with Power BI.',
    )
    customTheme: ThemeMetadata | None= Field(None,
        description='Defines a custom theme that is applied on top of the base theme.\nProperties not defined in the custom theme will fallback to using the base theme.',
    )


class ResourcePackage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None= None
    name: str
    type: ResourcePackageType
    items: list[ResourcePackageItem]
    disabled: bool | None= None


class Report(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: Literal['https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.1.0/schema.json'] = Field(
        ..., alias='$schema', description='Defines the schema to use for an item.'
    )
    themeCollection: ThemeCollection = Field(
        ...,
        description='Define a theme (built-in and/or a custom theme) to be used for this report.',
    )
    filterConfig: SchemaEmbedded | None= Field(None,
        description='Filters that apply to the entire report (all pages and all visuals).',
    )
    objects: ReportFormattingObjects | None= Field(None,
        description='Specifies the formatting to be set for different "objects" of a report.',
    )
    reportSource: ReportSource | None= Field(None, description='Defines how the report was created.'
    )
    publicCustomVisuals: list[str] | None= Field(None,
        description='Names of the custom visuals used in this report from AppSource.',
    )
    resourcePackages: list[ResourcePackage] | None= Field(None, description='Set of resources used within this report.'
    )
    organizationCustomVisuals: list[OrganizationCustomVisual] | None= Field(None,
        description='Names and metadata of the organization approved custom visuals used in the report.',
    )
    annotations: list[Annotation] | None= Field(None,
        description='Additional information to be saved (for example comments, readme, etc) for this report.',
    )
    dataSourceVariables: str | None= Field(None,
        description='A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.',
    )
    settings: ExplorationSettings | None= Field(None, description='Settings for the report.'
    )
    slowDataSourceSettings: ExplorationSlowDataSourceSettings | None= Field(None,
        description='Settings for slow data sources (for example turning all apply all button for filters).',
    )


class SchemaEmbedded(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filters: list[FilterContainer] | None= Field(None, description='Defines the definitions and metadata for the filters.'
    )
    filterSortOrder: FilterSortOrder | None= Field(None,
        description='Defines how the filters sorted - by name or custom sorting\nIf custom sorting, then ordinal property of every filter is used as the sort order,\nfilters where ordinal is skipped will be shown at the end; ordering will fallback to display name of the field.',
    )


class FilterContainer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ...,
        description='A unique name (across the whole report definition) defined for this filter.',
    )
    displayName: str | None= Field(None,
        description='An alternate name to use when displaying this filter - by default the display name of the field will be used, if there is no field or display name,\nthen restatement of the filter will be shown. Only applies to certain filter types.',
    )
    ordinal: float | None= Field(None,
        description='Defines the ordering of this filter w.r.t. other filters - only applies when Custom sort order is set.',
    )
    field: QueryExpressionContainer | None= Field(None, description='Defines the field from your data that is filtered.')
    type: Type | None= Field(None, description='The type of a filter.')
    filter: FilterDefinition | None= Field(None,
        description='Defines the actual filter definition - it is dependent on the type of filter.',
    )
    restatement: str | None= Field(None,
        description='A custom restatement to show for the filter - only applies to Passthrough filter type. For all other filters, a restatement is generated based on the filter definition.',
    )
    howCreated: HowCreated | None= Field(None, description='Specifies how this filter was first created.'
    )
    isHiddenInViewMode: bool | None= Field(None, description='Defines whether to hide this filter when viewing the report.'
    )
    isLockedInViewMode: bool | None= Field(None,
        description='Defines whether the filter value can be changed when viewing the report.',
    )
    objects: FilterContainerFormattingObjects | None= Field(None, description='Formatting for different "objects" of a filter card'
    )


class GeneralItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: FilterContainerFormattingObjectsProperties = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class FilterContainerFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    general: list[GeneralItem] | None= None


class Selector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[DataRepetitionSelector] | None= Field(None, description='Scope is defined by data bound to the visual.'
    )
    metadata: str | None= Field(None, description='Defines the scope to a specific field.'
    )
    id: str | None= Field(None, description='User defined scope.')
    highlightMatching: Type1 | None= Field(None,
        description='Describes how the Selector should behave towards Highlighted Values within the Scope matched by that Selector.',
    )
    hierarchyMatching: HierarchyMatching | None= Field(None,
        description='Describes how the selector matches hierarchy values.\nThis also changes how the query is generated for {@link DataViewScopeWildcard} selectors.\nNow those selectors can produce scopedValues for the level those match.\n\nThere are two ways that we can match values in the hierarchy:\n1.',
    )
    order: float | None= Field(None,
        description='Specifies a user-defined ordering of identical properties.\nSelector constructors should strive to monitonically increase this number across identical properties differing by id.',
    )


class DataViewObjectDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= None
    properties: dict[str, Any]


class DataRepetitionSelector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scopeId: QueryExpressionContainer | None= Field(None,
        description='Defines the intersection of scopes. For example - product color = red.',
    )
    wildcard: list[QueryExpressionContainer] | None= Field(None,
        description='Defines a match against all instances of a given DataView scope. Does not match Subtotals.\nDeprecated: - Use roles instead.',
    )
    roles: list[str] | None= Field(None, description='Matches against all fields in a role.'
    )
    total: list[QueryExpressionContainer] | None= Field(None, description='Matches against the totals and subtotals.')
    dataViewWildcard: DataViewWildcard | None= Field(None, description='Matches all instances or all totals or both.'
    )


class OutspacePaneItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: OutspacePane = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class SectionItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= Field(None,
        description='Defines the scope at which to apply the formatting for this object.\nCan also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.',
    )
    properties: Section = Field(
        ...,
        description='Describes the properties of the object to apply formatting changes to.',
    )


class ReportFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outspacePane: list[OutspacePaneItem] | None= None
    section: list[SectionItem] | None= None


Report.model_rebuild()
SchemaEmbedded.model_rebuild()
FilterContainer.model_rebuild()
GeneralItem.model_rebuild()
Selector.model_rebuild()
