{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"BU\",\"FP\",\"PayType\",\"SeparationReason\",\"Date\",\"Employee\",\"Ethnicity\",\"Gender\",\"AgeGroup\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "7ddd41c5-a1f5-477b-9712-84fdc7313c7d",
        "fromColumn": "date",
        "fromTable": "Employee",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "497871a2-f5e1-40ff-90d7-6f980ca1119a",
        "fromColumn": "FP",
        "fromTable": "Employee",
        "toColumn": "FP",
        "toTable": "FP"
      },
      {
        "name": "20c07ef2-2c50-4fd4-ad56-8b0e0e36ddc4",
        "fromColumn": "EthnicGroup",
        "fromTable": "Employee",
        "toColumn": "Ethnic Group",
        "toTable": "Ethnicity"
      },
      {
        "name": "539493ca-f3e3-4c1f-b14e-54cba661f036",
        "fromColumn": "Gender",
        "fromTable": "Employee",
        "toColumn": "ID",
        "toTable": "Gender"
      },
      {
        "name": "7c262a8a-d56f-4c97-95db-c0f56177e4cd",
        "fromColumn": "PayTypeID",
        "fromTable": "Employee",
        "toColumn": "PayTypeID",
        "toTable": "PayType"
      },
      {
        "name": "edfe54b9-43d8-4c14-a29d-f17ddb0dd421",
        "fromColumn": "BU",
        "fromTable": "Employee",
        "toColumn": "BU",
        "toTable": "BU"
      },
      {
        "name": "35cbfa94-d30d-4da9-8fb6-e7d469edb9bb",
        "fromColumn": "AgeGroupID",
        "fromTable": "Employee",
        "toColumn": "AgeGroupID",
        "toTable": "AgeGroup"
      },
      {
        "name": "1c53ee81-f20a-40a6-a5bd-97e57652fc88",
        "fromColumn": "TermReason",
        "fromTable": "Employee",
        "toColumn": "SeparationTypeID",
        "toTable": "SeparationReason"
      },
      {
        "name": "0f809af4-d31b-4977-a214-8f13fa42f41d",
        "fromColumn": "Date",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6f19fed3-1fc0-4f7a-878d-34aca93d6782"
      },
      {
        "name": "f496f9ad-5665-4785-a30e-b1bbcf7be215",
        "fromColumn": "MonthStartDate",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d2ea5b26-668d-4c17-b228-695669b066a6"
      },
      {
        "name": "b2a9d346-0212-432d-a1a9-57680b4a73ea",
        "fromColumn": "MonthEndDate",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c9dde99e-7ac1-4e8e-a5f2-c5ffc41d9cac"
      },
      {
        "name": "e020e64e-e74a-4b8f-bed8-e879143ea6d8",
        "fromColumn": "TermDate",
        "fromTable": "Employee",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_cc28ef26-f63a-4bc3-b357-93ab34cd6d9b"
      },
      {
        "name": "3e454a13-2d74-4769-b44d-91ce492acf1a",
        "fromColumn": "HireDate",
        "fromTable": "Employee",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c04ce649-6e25-466f-9bbc-faabfec0fe29"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "BU",
        "columns": [
          {
            "name": "BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "779dd929-d123-4ee5-905f-8ed5287806c6",
            "sourceColumn": "BU",
            "summarizeBy": "none"
          },
          {
            "name": "RegionSeq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0c1c9a2-142a-4222-81cd-b3801599e054",
            "sourceColumn": "RegionSeq",
            "summarizeBy": "none"
          },
          {
            "name": "VP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5686d7fb-ad68-4850-b926-62a8dbb1803e",
            "sourceColumn": "VP",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "mid([RegionSeq], 3,15)",
            "isDataTypeInferred": true,
            "lineageTag": "ebbda8e0-2c05-496a-9cea-e9d3b09a69dc",
            "sortByColumn": "RegionSeq",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "89ca23e1-674c-4ab0-96bd-f20677113e1f",
        "measures": [
          {
            "name": "Count of BU",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "COUNTA('BU'[BU])",
            "lineageTag": "1134fd8b-d59c-47d6-8a65-a419847617bd"
          }
        ],
        "partitions": [
          {
            "name": "BU",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"select distinct market BU,#(lf)  REGIONTITLE Region,#(lf)  MARKETDIRECTOR VP#(lf)from hr.bu\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"BU\", \"BU\"}, {\"Region\", \"RegionSeq\"}, {\"VP\", \"VP\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"BU\", type text}, {\"RegionSeq\", type text}, {\"VP\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FP",
        "columns": [
          {
            "name": "FP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e107760-5318-45fe-8f90-a1a8e3e9aa0e",
            "sourceColumn": "FP",
            "summarizeBy": "none"
          },
          {
            "name": "FPDesc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85394144-f60a-45a6-ade4-e975ebda1ba4",
            "sourceColumn": "FPDesc",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "99a5924f-9aa6-4fd8-b3f0-f2110ea2f56e",
        "partitions": [
          {
            "name": "FP",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT [HR].[FP].*   FROM [HR].[FP]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"FP\", \"FP\"}, {\"FPDesc\", \"FPDesc\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"FP\", type text}, {\"FPDesc\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PayType",
        "columns": [
          {
            "name": "PayTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1034f6dc-57f9-4611-9c26-c9c090f8ea54",
            "sourceColumn": "PayTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "PayType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64f662eb-93f9-496a-a95f-65f9d277ca5d",
            "sourceColumn": "PayType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "91a343c8-2f75-41ad-a018-9275a2e2b794",
        "partitions": [
          {
            "name": "PayGroup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"select distinct PayTypeID, [Hrly-Salaried] PayType#(lf)from [HR].[PayGroup]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"PayTypeID\", \"PayTypeID\"}, {\"PayType\", \"PayType\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"PayTypeID\", type text}, {\"PayType\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SeparationReason",
        "columns": [
          {
            "name": "SeparationTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "779c6021-160a-4e71-b2be-5b894fa76ab9",
            "sourceColumn": "SeparationTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "SeparationReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b44a63f1-229e-4a8f-bf90-eb63822e2c80",
            "sourceColumn": "SeparationReason",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "85b289cb-4757-434f-948d-42912318e2bb",
        "partitions": [
          {
            "name": "TermReason",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT distinct SeparationTypeID, [Vol-Invol] SeparationReason#(lf)  FROM [IP].[HR].[TermReason]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"SeparationTypeID\", \"SeparationTypeID\"}, {\"SeparationReason\", \"SeparationReason\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"SeparationTypeID\", type text}, {\"SeparationReason\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "__PBI_LegacyCustomDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isKey": true,
            "lineageTag": "7c140958-6aa7-4ec1-8d02-480ed922dd29",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6f19fed3-1fc0-4f7a-878d-34aca93d6782"
                },
                "isDefault": true,
                "relationship": "0f809af4-d31b-4977-a214-8f13fa42f41d"
              }
            ]
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "153dce9c-c865-404e-a361-a891f75bdfb9",
            "sortByColumn": "MonthNumber",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "ac4e7cc3-6280-4386-9695-de8720273f8d",
            "sourceColumn": "MonthNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee57b12c-c80c-491e-a4c1-e150850c7924",
            "sortByColumn": "PeriodNumber",
            "sourceColumn": "Period",
            "summarizeBy": "none"
          },
          {
            "name": "PeriodNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "a6f066e4-a4e9-4d2e-9b39-08f424671374",
            "sourceColumn": "PeriodNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "Qtr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "5c1f8e60-f1ff-49e2-98a5-14984e991664",
            "sourceColumn": "Qtr",
            "summarizeBy": "sum"
          },
          {
            "name": "QtrNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f8afca2-c26d-4624-b9ea-1e5b584b6a19",
            "sourceColumn": "QtrNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "2417645f-4ede-48d0-9b79-c7f2a8c22327",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "47615e8e-f2ab-47f1-a8f7-5223d34e4790",
            "sourceColumn": "Day",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthStartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5bc280b2-3cfc-4357-ae10-a64038e6533a",
            "sourceColumn": "MonthStartDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d2ea5b26-668d-4c17-b228-695669b066a6"
                },
                "isDefault": true,
                "relationship": "f496f9ad-5665-4785-a30e-b1bbcf7be215"
              }
            ]
          },
          {
            "name": "MonthEndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "966f7e60-947a-42fe-9b32-ef1c2ba56088",
            "sourceColumn": "MonthEndDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c9dde99e-7ac1-4e8e-a5f2-c5ffc41d9cac"
                },
                "isDefault": true,
                "relationship": "b2a9d346-0212-432d-a1a9-57680b4a73ea"
              }
            ]
          },
          {
            "name": "MonthIncrementNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": "([Year]-MIN([Year]))*12 +[MonthNumber]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "01c651f7-6477-433d-90f5-f0e1fbdefe10",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "YQM",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e6f669c8-e083-4c66-a932-64f037acc45b",
                "ordinal": 0
              },
              {
                "name": "QtrNumber",
                "column": "QtrNumber",
                "lineageTag": "7ff9d907-d13a-43e8-890f-c82012d18861",
                "ordinal": 1
              },
              {
                "name": "PeriodNumber",
                "column": "PeriodNumber",
                "lineageTag": "fee359b2-4104-4e51-9186-0e83643ee86b",
                "ordinal": 2
              }
            ],
            "lineageTag": "707a6be5-aa57-49eb-aed7-873f3ec99d83"
          }
        ],
        "lineageTag": "3c20188a-a3b3-4d8c-a2ac-0fe7dce040cb",
        "measures": [
          {
            "name": "Count of Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "COUNTA('Date'[Date])",
            "lineageTag": "d424a501-fe57-46c0-b0ed-ba65d9d40817"
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT [HR].[Date].*   FROM [HR].[Date]\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Date\", \"Date\"}, {\"Month\", \"Month\"}, {\"MonthNumber\", \"MonthNumber\"}, {\"Period\", \"Period\"}, {\"PeriodNumber\", \"PeriodNumber\"}, {\"Qtr\", \"Qtr\"}, {\"QtrNumber\", \"QtrNumber\"}, {\"Year\", \"Year\"}, {\"Day\", \"Day\"}, {\"MonthStartDate\", \"MonthStartDate\"}, {\"MonthEndDate\", \"MonthEndDate\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Date\", type datetime}, {\"Month\", type text}, {\"MonthNumber\", Int64.Type}, {\"Period\", type text}, {\"PeriodNumber\", Int64.Type}, {\"Qtr\", Int64.Type}, {\"QtrNumber\", type text}, {\"Year\", Int64.Type}, {\"Day\", Int64.Type}, {\"MonthStartDate\", type datetime}, {\"MonthEndDate\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Employee",
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "da8347f2-6b7d-48bf-9705-4a373ea262ad",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "EmplID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "46015b02-5523-4cde-afe6-6911648aeb25",
            "sourceColumn": "EmplID",
            "summarizeBy": "count"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3fbae66d-07dd-42a8-9a0a-c77e74b17fad",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "9122e7f0-3be6-41e9-9ddc-e789a93f016e",
            "sourceColumn": "Age",
            "summarizeBy": "sum"
          },
          {
            "name": "EthnicGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "522079dc-ae62-4383-bef1-11b56c439439",
            "sourceColumn": "EthnicGroup",
            "summarizeBy": "none"
          },
          {
            "name": "FP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c66260cc-f080-4774-b981-9b4ac29f2cfe",
            "sourceColumn": "FP",
            "summarizeBy": "none"
          },
          {
            "name": "TermDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "f0ced92e-ca81-465a-adc7-56cc8cd7d659",
            "sourceColumn": "TermDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_cc28ef26-f63a-4bc3-b357-93ab34cd6d9b"
                },
                "isDefault": true,
                "relationship": "e020e64e-e74a-4b8f-bed8-e879143ea6d8"
              }
            ]
          },
          {
            "name": "isNewHire",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": "IF(YEAR([date]) = YEAR([HireDate]) && MONTH([date])=MONTH([HireDate]), 1)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6ac8c542-152e-4495-9ad9-1af807c29b39",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "BU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0ad404f9-8ce2-4e6e-b7e7-205d85552520",
            "sourceColumn": "BU",
            "summarizeBy": "none"
          },
          {
            "name": "HireDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "isHidden": true,
            "lineageTag": "ca268af8-63a0-4dc1-af60-a90bf336bb63",
            "sourceColumn": "HireDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c04ce649-6e25-466f-9bbc-faabfec0fe29"
                },
                "isDefault": true,
                "relationship": "3e454a13-2d74-4769-b44d-91ce492acf1a"
              }
            ]
          },
          {
            "name": "PayTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7a437a37-75c8-4b8c-9110-c3c64fe514bd",
            "sourceColumn": "PayTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "TermReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8bacadd7-5472-48cc-b4cc-5598637d3c7f",
            "sourceColumn": "TermReason",
            "summarizeBy": "none"
          },
          {
            "name": "AgeGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": "IF([Age]<30, 1, IF([Age]<50, 2, 3))",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "74acfceb-16bf-4068-9dde-7c3ea2dc8fa3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "TenureDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF([date]-[HireDate]<0,[HireDate]-[date],[date]-[HireDate])",
            "isHidden": true,
            "lineageTag": "5ac6ad06-5d51-47cf-86c0-4f816510ad64",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "TenureMonths",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": "CEILING([TenureDays]/30, 1) -1",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b0ad6a54-5334-4abf-8f24-dd3e89f4fdd3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "BadHires",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF(OR((([HireDate]-[TermDate])*-1)>=61,ISBLANK([TermDate])),0,1)",
            "lineageTag": "1df76a6a-6e28-4ca2-b5ee-d16eb0402a97",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "1818a90f-9c42-466c-b63c-a1a7c51474dd",
        "measures": [
          {
            "name": "EmpCount",
            "expression": "CALCULATE(COUNT([EmplID]), FILTER(ALL('Date'[PeriodNumber]), 'Date'[PeriodNumber] = MAX('Date'[PeriodNumber])))",
            "formatString": "#,0",
            "lineageTag": "c0e6d18c-c307-4b0a-b2e3-bffc62fab2ea"
          },
          {
            "name": "Seps",
            "expression": "CALCULATE(COUNT([EmplID]), FILTER(Employee, NOT(ISBLANK(Employee[TermDate]))))",
            "formatString": "#,0",
            "lineageTag": "8252214a-19e7-474e-8e2c-fb134271afd5"
          },
          {
            "name": "Actives",
            "expression": "CALCULATE([EmpCount], FILTER(Employee, ISBLANK(Employee[TermDate])))",
            "formatString": "#,0",
            "lineageTag": "41b11325-9418-467a-8cd3-b43dde891c64"
          },
          {
            "name": "New Hires",
            "expression": "SUM([isNewHire])",
            "formatString": "#,0",
            "lineageTag": "1b3d9292-b51f-48f0-8908-aef8d3cbd8f9"
          },
          {
            "name": "AVG Tenure Days",
            "expression": "AVERAGE([TenureDays])",
            "formatString": "#,0",
            "lineageTag": "a72d32ed-c4fe-4e77-b5ab-912a9b0b46ea"
          },
          {
            "name": "AVG Tenure Months",
            "expression": "ROUND([AVG Tenure Days]/30, 1)-1",
            "formatString": "0",
            "lineageTag": "39677f32-3330-4b71-af0b-b4fbc18788c0"
          },
          {
            "name": "AVG Age",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "ROUND(AVERAGE([Age]), 0)",
            "lineageTag": "2fb5574d-6469-4d67-b9fb-d5fdf2accc84"
          },
          {
            "name": "Sum of BadHires",
            "expression": "SUM([BadHires])",
            "formatString": "#,0",
            "lineageTag": "73228d63-8f76-48b4-96cc-1e71afe43b4f"
          },
          {
            "name": "New Hires SPLY",
            "expression": "CALCULATE([New Hires],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0",
            "lineageTag": "af2466c4-db1b-44d9-adf4-ebb6c24a1635"
          },
          {
            "name": "Actives SPLY",
            "expression": "CALCULATE([Actives],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0",
            "lineageTag": "e8060931-9e92-484c-8f9b-6113868ad6c2"
          },
          {
            "name": "Seps SPLY",
            "expression": "CALCULATE([Seps],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0",
            "lineageTag": "5ae5842c-f2c6-4963-8f9b-ea98babc719b"
          },
          {
            "name": "EmpCount SPLY",
            "expression": "CALCULATE(COUNT([EmplID]), FILTER(ALL('Date'[PeriodNumber]), 'Date'[PeriodNumber] = MAX('Date'[PeriodNumber])),SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0",
            "lineageTag": "7cf8da84-faca-4ef9-8a2b-4f611a13b0ef"
          },
          {
            "name": "Seps YoY Var",
            "expression": "[Seps]-[Seps SPLY]",
            "formatString": "#,0",
            "lineageTag": "8741f3d5-d3e5-4193-98fd-58bf3de584f1"
          },
          {
            "name": "Actives YoY Var",
            "expression": "[Actives]-[Actives SPLY]",
            "formatString": "#,0",
            "lineageTag": "12aa4de4-5700-4ad9-a09e-2103e225b933"
          },
          {
            "name": "New Hires YoY Var",
            "expression": "[New Hires]-[New Hires SPLY]",
            "formatString": "#,0",
            "lineageTag": "71b00be1-c075-40ec-b38d-fd1f0a8b1e7d"
          },
          {
            "name": "Seps YoY % Change",
            "expression": "DIVIDE([Seps YoY Var], [Seps SPLY])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "0c32c220-6132-49be-b200-bbd6d525d417"
          },
          {
            "name": "Actives YoY % Change",
            "expression": "DIVIDE([Actives YoY Var], [Actives SPLY])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "a59107cc-09e7-456a-8cda-96cb43f19bb2"
          },
          {
            "name": "New Hires YoY % Change",
            "expression": "DIVIDE([New Hires YoY Var], [New Hires SPLY])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "cbadb500-3ce8-4f60-b9d7-fe8fd36b0a72"
          },
          {
            "name": "Bad Hires SPLY",
            "expression": "CALCULATE([Sum of BadHires],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0",
            "lineageTag": "398e1f76-232b-4034-b456-3d37e213aabc"
          },
          {
            "name": "Bad Hires YoY Var",
            "expression": "[Sum of BadHires]-[Bad Hires SPLY]",
            "formatString": "#,0",
            "lineageTag": "855c73f5-fc84-4f5a-afa7-0cbccf4b6359"
          },
          {
            "name": "Bad Hires YoY % Change",
            "expression": "DIVIDE([Bad Hires YoY Var], [Bad Hires SPLY])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "a104ec96-7d96-4bda-b891-6dcbc9babb6d"
          },
          {
            "name": "TO %",
            "expression": "DIVIDE([Seps], [Actives])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0c409527-1e68-4e11-b023-ecb3171cc69c"
          },
          {
            "name": "TO % Norm",
            "expression": "CALCULATE([TO %], all(Gender[Gender]), ALL(Ethnicity[Ethnicity]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e0dc8121-3435-4208-8813-b17b39d7109e"
          },
          {
            "name": "TO % Var",
            "expression": "[TO %]-[TO % Norm]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "28237fe1-8ec5-4197-a8b5-54f466b7650e"
          },
          {
            "name": "Sep%ofActive",
            "expression": "DIVIDE([Seps],[Actives])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f0c7189b-3a51-4a50-aa85-56cdf53b93af"
          },
          {
            "name": "Sep%ofSMLYActives",
            "expression": "DIVIDE([Seps SPLY],[Actives SPLY])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2be9e6c1-883f-4726-90b3-6df416274772"
          },
          {
            "name": "BadHire%ofActives",
            "expression": "DIVIDE([Sum of BadHires],[Actives])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "01502d39-b9ab-4629-973b-0475c9871dd5"
          },
          {
            "name": "BadHire%ofActiveSPLY",
            "expression": "DIVIDE([Bad Hires SPLY],[Actives SPLY])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bf579414-9f62-4a1d-a5fc-f696a75d1fe3"
          }
        ],
        "partitions": [
          {
            "name": "Employee",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\".\", \"IP\", [Query=\"SELECT dateadd(year, 1, d.date) Date#(lf)  ,Market BU#(lf)  ,[EmplID]#(lf)  ,iif([Gender]='M', 'C', 'D') Gender --  ,iif([Gender]='M', 'F', 'M') Gender#(lf)  ,[Age] - (2013 - year(d.date)) Age#(lf)  ,[EthnicGroup]#(lf)  ,[FP]#(lf)  ,dateadd(year, 1, [SenDate]) HireDate#(lf)  ,p.PayTypeID#(lf)  ,null [TermDate]#(lf)  ,null [TermReason]#(lf) FROM [IP].[HR].[AllEmps] E , [HR].[Date] d , [HR].[BU] b , hr.PayGroup p --, hr.TermReason t#(lf) where d.day = 1 and e.SenDate <= d.MonthEndDate and isnull(e.termdate, '9999-01-01') >= d.MonthEndDate and d.Date < '2014-01-01'#(lf)  and p.PayGroup = e.PayGroup#(lf)  and b.UNIT = e.Unit and [EmplID] % 2 = 0#(lf)union all#(lf)--seps#(lf)SELECT dateadd(year, 1, d.date) Date#(lf)    ,Market BU#(lf)      ,[EmplID]#(lf)      ,iif([Gender]='M', 'C', 'D') Gender#(lf)      ,[Age] - (2013 - year(d.date)) Age#(lf)      ,[EthnicGroup]#(lf)      ,[FP]#(lf)      ,dateadd(year, 1,[SenDate]) HireDate#(lf)      ,p.PayTypeID#(lf)      ,dateadd(year, 1, [TermDate]) [TermDate]#(lf)      ,t.[SeparationTypeID] [TermReason]#(lf)  FROM [IP].[HR].[AllEmps] E, [HR].[Date] d , [HR].[BU] b, hr.PayGroup p , hr.TermReason t#(lf) where d.day = 1 and e.TermDate <= d.MonthEndDate and e.TermDate >= d.MonthStartDate and d.Date < '2014-01-01'#(lf)  and p.PayGroup = e.PayGroup #(lf)  and t.[Term-Discharge]= e.[Term-Discharge]#(lf)  and b.UNIT = e.Unit and [EmplID] % 2 = 0\"]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"date\", \"date\"}, {\"EmplID\", \"EmplID\"}, {\"Gender\", \"Gender\"}, {\"Age\", \"Age\"}, {\"EthnicGroup\", \"EthnicGroup\"}, {\"FP\", \"FP\"}, {\"TermDate\", \"TermDate\"}, {\"BU\", \"BU\"}, {\"HireDate\", \"HireDate\"}, {\"PayTypeID\", \"PayTypeID\"}, {\"TermReason\", \"TermReason\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"date\", type datetime}, {\"EmplID\", Int64.Type}, {\"Gender\", type text}, {\"Age\", Int64.Type}, {\"EthnicGroup\", type text}, {\"FP\", type text}, {\"TermDate\", type datetime}, {\"BU\", type text}, {\"HireDate\", type datetime}, {\"PayTypeID\", type text}, {\"TermReason\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Ethnicity",
        "columns": [
          {
            "name": "Ethnic Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "efb1a6a5-bc5f-4646-bf37-0ebd05406fa8",
            "sourceColumn": "Ethnic Group",
            "summarizeBy": "none"
          },
          {
            "name": "Ethnicity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c391234b-fe25-4b08-95e5-fc7835a4f367",
            "sourceColumn": "Ethnicity",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "30dc6e8b-2ab9-4c09-9916-df8afd72fe27",
        "partitions": [
          {
            "name": "Ethnicity",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUXIvyi8tUHBUitWJVjKC853AfGM43xnMN4HzXcB8UzjfFcw3g/PdwHxzON9dKTYWAA==\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Column1\", \"Ethnic Group\"}, {\"Column2\", \"Ethnicity\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"Ethnic Group\", type text}, {\"Ethnicity\", type text}})",
                " in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Gender",
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9e1f99e8-3e65-46d0-91f5-09cde1117464",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7feb7e00-ab2d-433e-ac57-7677593e35b2",
            "sortByColumn": "Sort",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "6d843eb6-fe23-49c9-b054-e55dec540f69",
            "sourceColumn": "Sort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c5f601a6-944e-4e7e-a223-bded35598dc5",
        "partitions": [
          {
            "name": "Gender",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WclHSUfJNzEkFUoZKsTrRSs5AlltqLkTISCk2FgA=\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Column1\", \"ID\"}, {\"Column2\", \"Gender\"}, {\"Column3\", \"Sort\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"ID\", type text}, {\"Gender\", type text}, {\"Sort\", Int64.Type}})",
                " in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "AgeGroup",
        "columns": [
          {
            "name": "AgeGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "f1086f51-a9c5-4f66-8c04-4cfbb58da03c",
            "sourceColumn": "AgeGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "AgeGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da90bb2f-15b1-4c59-9780-20adc4d214d7",
            "sourceColumn": "AgeGroup",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "45ab7113-73c6-470a-bbbd-6079040598f1",
        "partitions": [
          {
            "name": "AgeGroup",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUYopNTAwTjY2UIrViVYyAgoYG+iaWIJ5xkCeqYG2UmwsAA==\", BinaryEncoding.Base64), Compression.Deflate))),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source, {{\"Column1\", \"AgeGroupID\"}, {\"Column2\", \"AgeGroup\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\", {{\"AgeGroupID\", Int64.Type}, {\"AgeGroup\", type text}})",
                " in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_92fd358c-bb4c-4d52-9f5b-e9a59dc2315d",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b1b8ac3f-43df-4a93-a270-5710c15dcf8e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7bf4d650-becd-4ff5-9653-5066ed1b09a2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "682b613d-fadc-4b74-a152-db36b8cf7aaf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a4f29a12-46e4-46e4-9130-282cf2058a42",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "246fca21-6b53-4521-9bd4-6da74177401b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "02512ae0-c43e-4303-9583-2f211cc5e1da",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7dd3561b-745d-4cd9-beac-4329fcb6caaf",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bb988823-fa37-4e61-b890-015e29065b19",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2b83b499-d8d5-4374-a03a-381ff5cbc1cc",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "dee06ff3-817f-43c3-b2a0-231a7065f6df",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2b52962d-08e1-4dfa-8711-456a4a7e2f9d",
                "ordinal": 3
              }
            ],
            "lineageTag": "ab428a8b-dfdc-4bce-9df2-910a563f85b7"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "387874a7-b20f-4aa0-b03b-90b686f2ebcb",
        "partitions": [
          {
            "name": "DateTableTemplate_92fd358c-bb4c-4d52-9f5b-e9a59dc2315d-a77c7bd2-b06b-4692-81d1-b28cb1313ae7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6f19fed3-1fc0-4f7a-878d-34aca93d6782",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6209c6c0-7243-4170-823f-70fead540407",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6e43c07f-ab5c-4a04-aea2-7a90204f6587",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8840c3d2-bd08-4f4b-8485-341334bdcfc5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "33c78218-60a9-4b8d-a9a7-eebc5b012d6b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4ca00b86-d2ea-4e07-b20e-6e66a45ac4f6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "65443303-4d46-4305-9f0b-7be387b22c97",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "86e12ca8-2a89-4328-a94b-cd540bd6150a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9c0905d3-2b60-4016-877e-23ece29cf763",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "93394797-9a35-4392-b4c6-d09336f02f5c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d46c4631-3096-4c98-9d5a-0f32ef30317c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d7455e41-c782-48e5-b54a-a2efc672b2a3",
                "ordinal": 3
              }
            ],
            "lineageTag": "7ccd457c-cfa0-47d0-874b-92d7195a55c4"
          }
        ],
        "isHidden": true,
        "lineageTag": "9d0d5fc5-1278-457e-b7aa-6dd1ee070af1",
        "partitions": [
          {
            "name": "LocalDateTable_6f19fed3-1fc0-4f7a-878d-34aca93d6782-18b38778-d461-40be-8bdc-5cabd9622731",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[Date])), 1, 1), Date(Year(MAX('Date'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d2ea5b26-668d-4c17-b228-695669b066a6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4ca2e945-bc0d-4bd7-bea2-83e31521113c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0b585acc-8e90-4e07-bf3c-c7c433dc2450",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8b06f0d4-c7eb-4082-b66d-86eb5b22af95",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e7d89df4-9870-4bf8-8826-72558e22b2e8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e8282ea9-e3c8-4164-934a-75b9c8a7e2d0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f48c47a6-8640-4058-8ba9-d2540319366d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "43cfe450-b52b-426a-a222-98ccb8c2fd4b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "56aa95d2-6c12-433e-a7bd-19c47b7e1de8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "df2b7bbe-70e8-41a3-b6be-6ebf3ef3510e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4b3a6e0c-ac85-46b2-86aa-c81ed51b8e5a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "226e4247-fd84-40a7-b132-e71a64405264",
                "ordinal": 3
              }
            ],
            "lineageTag": "e01c9362-cbea-4645-9417-00f4b622a7d5"
          }
        ],
        "isHidden": true,
        "lineageTag": "6ff67b22-8564-45ac-b774-51361b28d391",
        "partitions": [
          {
            "name": "LocalDateTable_d2ea5b26-668d-4c17-b228-695669b066a6-4c3da6c6-9d21-4e9f-abd6-8f10391041fe",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[MonthStartDate])), 1, 1), Date(Year(MAX('Date'[MonthStartDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c9dde99e-7ac1-4e8e-a5f2-c5ffc41d9cac",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5238cd09-e6b9-4e8b-ba1c-a59b532917ef",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "41eeb4f1-650e-4b6f-9cf5-63d5066f40cd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ac847172-6d9c-4fb0-b982-b7a838265ed3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7018a12e-bb95-4b38-892c-47d9cc373a98",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "215a2abd-736a-4df2-b41b-3a8886f43ecd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cc6808fe-a8a0-4dd1-9de6-e18542d1c356",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a9eb110-e565-4baf-9ecf-55c200a9052e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e3e30c92-34ae-450d-a180-b7c9da6b9a0e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ae3a86a3-60c4-4bb5-af23-22908efde846",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "47c493ca-0643-402e-bf8f-83646a704e9c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "751ce8ee-3d62-438a-b374-f2acd63f9c97",
                "ordinal": 3
              }
            ],
            "lineageTag": "17357b79-50e9-4cf7-801a-4381bb163a2d"
          }
        ],
        "isHidden": true,
        "lineageTag": "5c04451a-5d33-4010-84e4-817581ed2834",
        "partitions": [
          {
            "name": "LocalDateTable_c9dde99e-7ac1-4e8e-a5f2-c5ffc41d9cac-fda95d47-f471-4e23-a11c-368e4a09cd75",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[MonthEndDate])), 1, 1), Date(Year(MAX('Date'[MonthEndDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_cc28ef26-f63a-4bc3-b357-93ab34cd6d9b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "156ab7d9-58d3-4528-b512-0fb4f78b9943",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "536e7b19-89ac-4d90-8ec6-6cf81441d69b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9852f0a8-54b8-476e-8b77-84f95e94e30b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1ad9cb81-43b9-42b8-8ab8-d1ad1c7dd693",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "98790e3b-adf9-4d9e-95aa-557556ffad09",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9bfe1d4b-45a9-4263-b4ab-6e73c591d2e6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5525ebe0-5e41-4c93-a889-62279dc3f001",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "50094bd0-fb7c-4a4b-b43a-d964d6f4f0bd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ad38ce13-cb1a-44ad-baff-5bf93b861048",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "59c7ca8e-b099-48fe-8f50-569e41ab79b1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "045905da-9d13-4d5c-8937-c1d475886ac5",
                "ordinal": 3
              }
            ],
            "lineageTag": "c858f31d-1f8d-4680-bb05-b6b0682c05c8"
          }
        ],
        "isHidden": true,
        "lineageTag": "e8765df0-c593-461b-8c13-29fc091976d3",
        "partitions": [
          {
            "name": "LocalDateTable_cc28ef26-f63a-4bc3-b357-93ab34cd6d9b-83843428-aaf8-48a2-a87d-94f90c4f36b7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Employee'[TermDate])), 1, 1), Date(Year(MAX('Employee'[TermDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c04ce649-6e25-466f-9bbc-faabfec0fe29",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "20a1957f-b678-4f9d-9dc7-8c73d60ee7db",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fe170271-4619-4967-a4ed-b9077e7eb855",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8fdc343a-997c-45aa-b07d-df49093f2665",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3e781896-dba8-4aed-a9ef-34bb319f02db",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fa313364-e95b-45d4-a059-deac73a92110",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5a63ee01-5176-4011-9ab6-d3806e90cf66",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fc94f624-a2a3-4ea1-bf84-691c44526a11",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "39225891-824a-4cd6-bb95-dac571256568",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ddfc2e25-2148-477b-800d-8f6e9c1bbd8c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a98cf2ed-3dd9-4090-8c91-3fcf422544b5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d46be1d4-d613-44eb-94a2-1f186b112429",
                "ordinal": 3
              }
            ],
            "lineageTag": "001f8126-27cb-47a5-b614-1aad264cd909"
          }
        ],
        "isHidden": true,
        "lineageTag": "1520a4cb-456e-4aa7-9d3e-3846e8267e7d",
        "partitions": [
          {
            "name": "LocalDateTable_c04ce649-6e25-466f-9bbc-faabfec0fe29-effb8a4b-4446-46fa-b675-98489db2a49a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Employee'[HireDate])), 1, 1), Date(Year(MAX('Employee'[HireDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}