#!/usr/bin/env python3
"""Generate in-memory TMDL fixture test files from pbi-samples.

Run from the pybi project root:

    python scripts/generate_tmdl_fixtures.py

Outputs one self-contained test file per SemanticModel sample into
``tests/unit/tmdl/``.  Each file embeds the sample's TMDL content as a Python
dict so tests require no filesystem I/O and no access to the pbi-samples repo.

Re-run whenever pbi-samples changes to refresh the snapshots.
"""

import sys
from datetime import date
from pathlib import Path

# Allow running from project root without installing the package
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from pybi.serialization.parsers.tmdl.grammar import DEFINITION_PREFIX  # noqa: E402
from pybi.serialization.parsers.tmdl.loader import TMDLPartsLoader  # noqa: E402
from pybi.serialization.transport.local import LocalTransport  # noqa: E402

SAMPLES_ROOT = Path("../pbi-samples/pbi/pbir/11.25")
OUTPUT_DIR = Path("tests/unit/tmdl")
TODAY = date.today().isoformat()


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------


def discover_samples(root: Path) -> list[tuple[str, Path]]:
    """Return (slug, path) for every *.SemanticModel directory under root."""
    results: list[tuple[str, Path]] = []
    for subdir in sorted(root.iterdir()):
        if not subdir.is_dir():
            continue
        for model_dir in sorted(subdir.iterdir()):
            if model_dir.is_dir() and model_dir.name.endswith(".SemanticModel"):
                slug = subdir.name.replace("-", "_")
                results.append((slug, model_dir))
    return results


# ---------------------------------------------------------------------------
# Data extraction
# ---------------------------------------------------------------------------


def extract_tmdl_files(sample_path: Path) -> dict[str, str]:
    """Read definition/*.tmdl files as {rel_path_without_prefix: text}."""
    parts = LocalTransport().read_parts(sample_path)
    tmdl: dict[str, str] = {}
    for p in parts:
        if p.path.startswith(DEFINITION_PREFIX) and p.path.endswith(".tmdl"):
            key = p.path[len(DEFINITION_PREFIX) :]
            tmdl[key] = p.as_text()
    return tmdl


def compute_metadata(tmdl_files: dict[str, str]) -> dict:
    """Parse tmdl_files once to capture expected counts for snapshot assertions."""
    data = TMDLPartsLoader(tmdl_files).load()
    model = data["model"]
    tables = model.tables or []
    return {
        "compatibility_level": data["compatibilityLevel"],
        "table_count": len(tables),
        "relationship_count": len(model.relationships or []),
        "expression_count": len(model.expressions or []),
        "culture_count": len(model.cultures or []),
    }


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------


def _render_tmdl_dict(tmdl_files: dict[str, str]) -> str:
    lines = ["TMDL_FILES: dict[str, str] = {"]
    for path in sorted(tmdl_files):
        lines.append(f"    {repr(path)}: {repr(tmdl_files[path])},")
    lines.append("}")
    return "\n".join(lines)


def render_test_file(
    slug: str,
    source_path: Path,
    tmdl_files: dict[str, str],
    meta: dict,
) -> str:
    sample_label = slug.replace("_", "-")
    tmdl_dict = _render_tmdl_dict(tmdl_files)

    return f"""\
# Auto-generated by scripts/generate_tmdl_fixtures.py: do not edit manually.
# Source: {source_path}
# Generated: {TODAY}

\"\"\"In-memory TMDL roundtrip tests for the {sample_label} sample.

TMDL_FILES is a snapshot of the sample's definition/ folder embedded as a
Python dict so tests run without any filesystem I/O.  Re-run
``scripts/generate_tmdl_fixtures.py`` to refresh snapshots from pbi-samples.
\"\"\"

from pybi.semanticmodel.definition import SemanticModelDefinition
from pybi.serialization.parsers.tmdl.loader import TMDLPartsLoader
from pybi.serialization.parsers.tmdl.writer import TMDLPartsWriter


{tmdl_dict}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load() -> SemanticModelDefinition:
    return SemanticModelDefinition(**TMDLPartsLoader(TMDL_FILES).load())


def _roundtrip() -> tuple[SemanticModelDefinition, SemanticModelDefinition]:
    sm = _load()
    written = TMDLPartsWriter().write(sm)
    sm2 = SemanticModelDefinition(**TMDLPartsLoader(written).load())
    return sm, sm2


# ---------------------------------------------------------------------------
# Parse tests
# ---------------------------------------------------------------------------


def test_parse_succeeds():
    assert _load() is not None


def test_compatibility_level():
    assert _load().compatibilityLevel == {meta["compatibility_level"]}


def test_table_count():
    assert len(_load().model.tables) == {meta["table_count"]}


# ---------------------------------------------------------------------------
# Roundtrip tests
# ---------------------------------------------------------------------------


def test_roundtrip_table_count():
    sm1, sm2 = _roundtrip()
    assert len(sm1.model.tables) == len(sm2.model.tables)


def test_roundtrip_all_table_names_preserved():
    sm1, sm2 = _roundtrip()
    assert {{t.name for t in sm1.model.tables}} == {{t.name for t in sm2.model.tables}}


def test_roundtrip_relationship_count():
    sm1, sm2 = _roundtrip()
    assert len(sm1.model.relationships or []) == len(sm2.model.relationships or [])


def test_roundtrip_expression_count():
    sm1, sm2 = _roundtrip()
    assert len(sm1.model.expressions or []) == len(sm2.model.expressions or [])


def test_roundtrip_culture_count():
    sm1, sm2 = _roundtrip()
    assert len(sm1.model.cultures or []) == len(sm2.model.cultures or [])


def test_roundtrip_column_counts_per_table():
    sm1, sm2 = _roundtrip()
    counts1 = {{t.name: len(t.columns or []) for t in sm1.model.tables}}
    counts2 = {{t.name: len(t.columns or []) for t in sm2.model.tables}}
    assert counts1 == counts2


def test_roundtrip_measure_counts_per_table():
    sm1, sm2 = _roundtrip()
    counts1 = {{t.name: len(t.measures or []) for t in sm1.model.tables}}
    counts2 = {{t.name: len(t.measures or []) for t in sm2.model.tables}}
    assert counts1 == counts2


def test_roundtrip_partition_counts_per_table():
    sm1, sm2 = _roundtrip()
    counts1 = {{t.name: len(t.partitions or []) for t in sm1.model.tables}}
    counts2 = {{t.name: len(t.partitions or []) for t in sm2.model.tables}}
    assert counts1 == counts2
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    if not SAMPLES_ROOT.exists():
        print(
            f"ERROR: {SAMPLES_ROOT} not found.\n"
            "Clone https://github.com/willianmh/pbi-samples next to this repo."
        )
        sys.exit(1)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    init_file = OUTPUT_DIR / "__init__.py"
    if not init_file.exists():
        init_file.write_text("")

    samples = discover_samples(SAMPLES_ROOT)
    if not samples:
        print(f"ERROR: No *.SemanticModel directories found under {SAMPLES_ROOT}")
        sys.exit(1)

    print(f"Found {len(samples)} sample(s). Generating test files into {OUTPUT_DIR}/")

    for slug, sample_path in samples:
        print(f"  {slug}: {sample_path.name} ... ", end="", flush=True)
        try:
            tmdl_files = extract_tmdl_files(sample_path)
            meta = compute_metadata(tmdl_files)
            content = render_test_file(slug, sample_path, tmdl_files, meta)
            out_path = OUTPUT_DIR / f"test_{slug}_roundtrip.py"
            out_path.write_text(content, encoding="utf-8")
            print(
                f"OK ({meta['table_count']} tables, "
                f"{meta['relationship_count']} rels, "
                f"{len(tmdl_files)} tmdl files)"
            )
        except Exception as exc:
            print(f"FAILED: {exc}")
            raise

    print("Done.")


if __name__ == "__main__":
    main()
