"""Automation script for generating Pydantic V2 models from Power BI JSON schemas.

This script solves the key challenge with ``datamodel-codegen``: when schemas
reference other schemas via ``$ref``, the tool inlines all definitions, causing
massive class duplication (e.g., ``QueryExpressionContainer`` exploding into 47
numbered variants).

Usage::

    python scripts/generate_models.py
    python scripts/generate_models.py --dry-run
    python scripts/generate_models.py --schema-root /path/to/schemas
    python scripts/generate_models.py --clean

Dependencies:
    - ``datamodel-code-generator`` (pip install datamodel-code-generator)
    - Power BI JSON schemas in the directory pointed to by ``--schema-root``
      (default: ``DEFAULT_SCHEMA_ROOT``, currently a hardcoded absolute path).

Architecture / Pipeline Stages:
    The main entry point is :func:`generate_all`, which orchestrates the
    following phases:

    1. **Discovery**: :func:`discover_schemas` performs a BFS walk starting
       from ``TARGET_SCHEMAS``, parsing each JSON file for ``$ref`` links to
       discover transitive dependencies.  The result is a dict of
       :class:`SchemaInfo` objects.

    2. **Ordering**: :func:`topological_sort` (Kahn's algorithm) computes a
       generation order so that base schemas are generated before the schemas
       that depend on them.

    3. **Code generation**: :func:`run_codegen` shells out to
       ``datamodel-codegen`` for each schema (with retry logic).

    4. **Post-processing**: the generated Python source goes through several
       transforms applied in order:

       a. :func:`remove_handcrafted_classes`: strip classes that have
          hand-crafted implementations and add an import instead
          (``semanticQuery`` only).
       b. :func:`deduplicate_against_registry`: remove classes already
          generated by a dependency schema and replace with cross-module
          imports.  Uses :class:`ClassRegistry` with structural-signature
          matching for safety.
       c. :func:`merge_numbered_variants`: collapse numbered variants
          (e.g., ``Foo1``-``Foo47``) into a single ``Foo`` class.
       d. :func:`_fix_optional_field_defaults`: normalise ``Field(False, …)``
          to ``Field(None, …)`` on ``Optional`` fields.
       e. :func:`_apply_post_generation_fixes`: apply schema-specific
          field-type corrections from ``POST_GENERATION_FIELD_FIXES``.

    5. **Registration**: surviving classes are registered in the
       :class:`ClassRegistry` so later schemas can deduplicate against them.

    6. **Packaging**: :func:`create_init_files` and
       :func:`create_top_level_init` emit ``__init__.py`` files for the
       versioned module tree.

Key Design Decisions:
    - **First-wins registration**: :meth:`ClassRegistry.register` stores the
      first schema that defines a class.  All subsequent schemas that generate
      the same class (with a matching structural signature) replace the local
      definition with an import.
    - **Signature-based substitution**: To avoid silently replacing a class
      whose structure has diverged, the registry compares SHA-1 hashes of
      normalised class bodies.  Only exact structural matches are substituted.
    - **Hand-crafted override**: A curated set of classes
      (``HANDCRAFTED_CLASSES``) is pre-registered with a sentinel signature
      (``"__handcrafted__"``).  These are always substituted with a wildcard
      import from ``expressions``.
    - **Last-version-wins init files**: When multiple versions of the same
      schema are generated (e.g., ``semanticQuery/1.2.0`` and ``1.3.0``), the
      schema-level ``__init__.py`` is overwritten each time.  Only the last
      version processed ends up re-exported.  Because :func:`topological_sort`
      is stable and versions are listed in ascending order in
      ``TARGET_SCHEMAS``, the *latest* version wins.

Known Issues / Future Refactor Notes:
    1. **Sequential class removal is position-fragile**: Functions that remove
       class blocks one at a time (``deduplicate_against_registry``,
       ``remove_handcrafted_classes``, ``_promote_variant_to_base``) mutate the
       source string between removals.  This works only because
       ``find_class_block`` re-searches the modified string each iteration, but
       is O(n*m) and would break if two removals overlapped.  Collecting all
       blocks first and removing in reverse offset order would be safer.

    2. **``_deduplicate_list_items`` regex is over-broad**: The pattern
       ``\\[([^\\[\\]]+)\\]`` matches *any* square-bracketed content, not just
       type annotations.  It could theoretically corrupt list comprehensions or
       string literals.  Acceptable for machine-generated code, but should be
       constrained in a refactor.

    3. **Global ``re.sub`` for variant renaming**: In
       ``merge_numbered_variants``, variant names are replaced with a blanket
       ``\\b`` word-boundary regex that also matches inside string literals,
       comments, and ``description=`` Field arguments.

    4. **``_make_fields_optional`` substring check**: The guard
       ``"None" in full_field`` is a substring match and could mis-fire on
       identifiers that contain "None" (e.g., ``isNoneValue``).

    5. **``ModuleNotFoundError`` / ``ImportError`` classified as transient**:
       These are deterministic failures and retrying will not resolve them.

    6. **``_insert_imports`` fragile import detection**: The heuristic that
       finds "the last import line" does not distinguish top-level imports from
       imports inside class bodies or string literals.  Safe for
       ``datamodel-codegen`` output, but fragile for arbitrary Python.

    7. **``DEFAULT_SCHEMA_ROOT`` is a hardcoded absolute path**: Not portable.
       Other developers must always pass ``--schema-root``.
"""

from __future__ import annotations

import argparse
import hashlib
import logging
import re
import shutil
import subprocess
import sys
import textwrap
from collections import defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_SCHEMA_ROOT = Path(
    r"/Users/willian/Documents/coding/json-schemas/fabric/item/report/definition"
)
PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_ROOT = PROJECT_ROOT / "src" / "pybi" / "report" / "pbir" / "models"

# Target schemas to generate: (directory_name, version, schema_filename)
# Order does NOT matter - the script resolves dependency order automatically.
TARGET_SCHEMAS: list[tuple[str, str, str]] = [
    ("semanticQuery", "1.2.0", "schema.json"),
    ("semanticQuery", "1.3.0", "schema.json"),
    ("semanticQuery", "1.4.0", "schema.json"),
    ("formattingObjectDefinitions", "1.4.0", "schema.json"),
    ("formattingObjectDefinitions", "1.5.0", "schema.json"),
    ("filterConfiguration", "1.2.0", "schema-embedded.json"),
    ("filterConfiguration", "1.3.0", "schema-embedded.json"),
    ("visualConfiguration", "2.2.0", "schema-embedded.json"),
    ("visualConfiguration", "2.3.0", "schema-embedded.json"),
    ("visualContainer", "2.3.0", "schema.json"),
    ("visualContainer", "2.4.0", "schema.json"),
    ("visualContainer", "2.5.0", "schema.json"),
    ("visualContainer", "2.6.0", "schema.json"),
    ("visualContainer", "2.7.0", "schema.json"),
    # PBIR-specific schemas
    # ("versionMetadata", "1.0.0", "schema.json"), # There is a bug in the script that removes the version metadata
    ("pagesMetadata", "1.0.0", "schema.json"),
    ("page", "1.4.0", "schema.json"),
    ("page", "2.0.0", "schema.json"),
    ("page", "2.1.0", "schema.json"),
    ("report", "3.0.0", "schema.json"),
    ("report", "3.1.0", "schema.json"),
    ("report", "3.2.0", "schema.json"),
    ("bookmarksMetadata", "1.0.0", "schema.json"),
    ("bookmark", "1.4.0", "schema.json"),
    ("bookmark", "2.0.0", "schema.json"),
    ("bookmark", "2.1.0", "schema.json"),
    ("reportExtension", "1.0.0", "schema.json"),
    ("visualContainerMobileState", "2.2.0", "schema.json"),
]

# datamodel-codegen flags shared across all invocations
CODEGEN_BASE_FLAGS: list[str] = [
    "--input-file-type",
    "jsonschema",
    "--output-model-type",
    "pydantic_v2.BaseModel",
    "--use-union-operator",
    "--use-standard-collections",
    "--collapse-root-models",
    "--reuse-model",
    "--collapse-reuse-models",
    "--disable-timestamp",
    "--target-python-version",
    "3.10",
]

# Maximum acceptable lines before triggering dedup warnings
MAX_LINES_WARN = 3000

# ---------------------------------------------------------------------------
# Hand-crafted model configuration
# ---------------------------------------------------------------------------

# Classes that are hand-crafted and should not be auto-generated.
# These are imported from the expressions module instead.
HANDCRAFTED_CLASSES: set[str] = {
    # Main container
    "QueryExpressionContainer",
    # Expression base
    "Expression",
    # Source references
    "StandaloneSourceRefExpression",
    "QuerySourceRefExpression",
    # Property/field references
    "QueryColumnExpression",
    "QueryMeasureExpression",
    "QueryHierarchyExpression",
    "QueryHierarchyLevelExpression",
    "QueryPropertyVariationSourceExpression",
    "QueryGroupRefExpression",
    # Aggregations
    "QueryAggregationExpression",
    "QueryMinExpression",
    "QueryMaxExpression",
    "QueryPercentileExpression",
    # Logical/boolean
    "QueryBinaryExpression",
    "QueryNotExpression",
    "QueryContainsExpression",
    "QueryStartsWithExpression",
    "QueryExistsExpression",
    "QueryComparisonExpression",
    "QueryInExpression",
    "QueryBetweenExpression",
    # Literals and values
    "QueryLiteralExpression",
    "QueryDefaultValueExpression",
    "QueryAnyValueExpression",
    "QueryNowExpression",
    # Date/time
    "QueryDateSpanExpression",
    "QueryDateAddExpression",
    # Arithmetic
    "QueryArithmeticExpression",
    "QueryFloorExpression",
    "QueryDiscretizeExpression",
    # Scoped/filtered
    "QueryScopedEvalExpression",
    "QueryFilteredEvalExpression",
    # Subquery/transform
    "QuerySubqueryExpression",
    "QueryTransformTableRefExpression",
    "QueryTransformOutputRoleRefExpression",
    # Visual/sparkline
    "QuerySparklineDataExpression",
    "QueryVisualTopNExpression",
    # Native expressions
    "QueryExpressionContentCache",
    "QueryNativeVisualCalc",
    "QueryNativeMeasure",
    "QueryNativeColumn",
    # Formatting/color
    "QueryFillRuleExpression",
    "QueryThemeDataColorExpression",
    "QueryConditionalExpression",
    "QueryCase",
    # References
    "QueryResourcePackageItem",
    "QueryRoleRefExpression",
    "QuerySummaryValueRefExpression",
    "QueryAllRolesRefExpression",
    "QuerySelectRefExpression",
    # Query structure
    "EntitySource",
    "QueryFilter",
    "QuerySortClause",
    "AxisGroup",
    "Axis",
    "QueryTransformTableColumn",
    "QueryTransformTable",
    "QueryTransformInput",
    "QueryTransformOutput",
    "QueryTransform",
    "QueryDefinition",
    "FilterDefinition",
}

# Import statement for hand-crafted classes
HANDCRAFTED_IMPORT = "from ..expressions import *"

# Regex pattern to identify QueryExpressionContainer numbered variants
_QUERY_EXPR_CONTAINER_VARIANT = re.compile(r"^QueryExpressionContainer\d+$")

# ---------------------------------------------------------------------------
# Post-generation field type corrections
# ---------------------------------------------------------------------------

# Schema-specific field type fixes applied AFTER all normal post-processing.
# These correct known naming collisions where the class registry incorrectly
# maps a field type to the wrong imported class.
#
# Format: {schema_key: [(cls_name, old_fragment, new_fragment, extra_imports)]}
#   - cls_name:      informational only (for logging)
#   - old_fragment:  substring in the generated source to replace
#   - new_fragment:  replacement substring
#   - extra_imports: list of additional import lines needed
POST_GENERATION_FIELD_FIXES: dict[str, list[tuple[str, str, str, list[str]]]] = {
    # visualContainer/2.3.0 fixes
    # Problem 1: datamodel-codegen resolves `visual`'s `$ref` to visualConfiguration
    # schema-embedded.json as `SchemaEmbedded`.  The class registry already has
    # `SchemaEmbedded` registered from page/2.0.0 (a filter-only model), so dedup
    # replaces the correct `VisualConfiguration` type with the wrong page model.
    # Fix: restore the correct type.
    "visualContainer/2.3.0": [
        (
            "VisualContainer.visual",
            "visual: SchemaEmbedded | None",
            "visual: VisualConfiguration | None",
            ["from ...visualconfiguration.v2_2_0.model import VisualConfiguration"],
        ),
        (
            "VisualContainer.filterConfig",
            "filterConfig: SchemaEmbeddedModel | None",
            "filterConfig: dict[str, Any] | None",
            [],
        ),
        # Problem 2: `howCreated` enum doesn't include newer Power BI values
        # (e.g. 'InsertVisualButton').  Use str for forward-compatibility.
        (
            "VisualContainer.howCreated",
            "howCreated: HowCreated | None",
            "howCreated: str | None",
            [],
        ),
    ],
    # visualContainer/2.4.0 fixes
    # Same collision/forward-compatibility issues as 2.3.0.
    "visualContainer/2.4.0": [
        (
            "VisualContainer.visual",
            "visual: SchemaEmbedded | None",
            "visual: VisualConfiguration | None",
            ["from ...visualconfiguration.v2_2_0.model import VisualConfiguration"],
        ),
        (
            "VisualContainer.filterConfig",
            "filterConfig: SchemaEmbeddedModel | None",
            "filterConfig: dict[str, Any] | None",
            [],
        ),
        (
            "VisualContainer.howCreated",
            "howCreated: HowCreated | None",
            "howCreated: str | None",
            [],
        ),
    ],
    # filterconfiguration/1.2.0 fixes
    # Problem: filter `type` field is typed as an integer-only enum, but real PBIR
    # data also carries legacy string values like 'Categorical'.
    "filterconfiguration/1.2.0": [
        (
            "FilterContainer.type",
            "type: Type | None= Field(None, description='The type of a filter.')",
            (
                "type: int | str | None= Field("
                "None, description='The type of a filter. "
                "Accepts both numeric (PBIR) and string (legacy) representations.')"
            ),
            [],
        ),
    ],
    # visualConfiguration/2.2.0 fixes
    # Problem: class-name collision can map VisualContainerFormattingObjects.general
    # to filterconfiguration.GeneralItem after regeneration. Force a stable,
    # hand-crafted item type owned by visualconfiguration.
    "visualConfiguration/2.2.0": [
        (
            "VisualContainerFormattingObjects.general",
            "general: list[GeneralItem] | None= None",
            "general: list[VisualContainerGeneralItem] | None= None",
            [
                (
                    "from .general_item import "
                    "VisualContainerGeneralFormattingObjects, VisualContainerGeneralItem"
                )
            ],
        ),
    ],
}

# ---------------------------------------------------------------------------
# Optional-field default normalisation
# ---------------------------------------------------------------------------

# Regex that matches: <field_name>: <type> | None= Field(<non-None-default>,
# (detecting non-None primitive/string defaults for Optional fields)
_OPTIONAL_FIELD_BAD_DEFAULT = re.compile(
    r"(\b\w+: [^\n]+\|\s*None\s*=\s*Field\()"  # field_name: SomeType | None= Field(
    r"\s*(?!None\b)(?!\.\.\.\b)"  # not already None / required sentinel
    r"([^,\n]+)"  # existing default token
    r"\s*,",
    re.MULTILINE,
)

# Repair pattern for malformed output like Field(None, False, description=...)
_FIELD_NONE_DOUBLE_POSITIONAL = re.compile(
    r"Field\(None,\s*([^)]*?),\s*description=",
    re.DOTALL,
)


def _fix_optional_field_defaults(source: str) -> str:
    """Replace non-None primitive defaults on ``| None`` fields with ``None``.

    ``datamodel-codegen`` copies JSON Schema ``default`` values verbatim into
    ``Field(default, ...)``.  For Python models that use ``exclude_none=True``
    during serialisation, a non-None default causes the field to always appear
    in the serialised output even when the input data omitted it.

    After the main replacement, a defensive cleanup pass removes double-
    positional arguments of the form ``Field(None, <positional>, description=…)``
    that can be left behind by earlier transforms.

    Args:
        source: Complete Python source text of a generated model file.

    Returns:
        The source with all non-None defaults on Optional fields replaced by
        ``None``.  The number of replacements is logged at INFO level.

    Examples fixed::

        isToggled: bool | None= Field(False, ...)  →  Field(None, ...)
        highlightMatching: HM | None= Field(0, ...)  →  Field(None, ...)
        hierarchyMatching: HM | None= Field('long…', ...)  →  Field(None, ...)
    """
    count = [0]

    def _replace(match: re.Match) -> str:
        count[0] += 1
        return match.group(1) + "None,"

    result = _OPTIONAL_FIELD_BAD_DEFAULT.sub(_replace, source)

    # Defensive cleanup: if an older transform produced `Field(None, X, description=...)`
    # and X is positional (not keyword arg), drop X.
    def _cleanup_double_positional(match: re.Match) -> str:
        inner = match.group(1)
        if "=" in inner:
            return match.group(0)
        return "Field(None, description="

    result = _FIELD_NONE_DOUBLE_POSITIONAL.sub(_cleanup_double_positional, result)

    if count[0]:
        log.info("  Fixed %d non-None Optional field default(s)", count[0])
    return result


def _replace_constr_with_annotated(source: str) -> str:
    """Replace ``constr(...)`` with ``Annotated[str, StringConstraints(...)]``.

    ``datamodel-codegen`` emits Pydantic V1-style ``constr(pattern=..., max_length=...)``
    calls.  This function rewrites them to the modern Pydantic V2 form using
    ``Annotated`` and ``StringConstraints``, and adjusts the import block
    accordingly.

    Uses parenthesis counting instead of a regex to correctly handle pattern
    strings that contain ``)`` characters (e.g. ``r'^(a|b)$'``).
    """
    if "constr(" not in source:
        return source

    result: list[str] = []
    i = 0
    changed = False
    while i < len(source):
        if source[i : i + 7] == "constr(":
            start = i + 7  # position after the opening (
            depth = 1
            j = start
            while j < len(source) and depth > 0:
                if source[j] == "(":
                    depth += 1
                elif source[j] == ")":
                    depth -= 1
                j += 1
            args = source[start : j - 1]
            result.append(f"Annotated[str, StringConstraints({args})]")
            i = j
            changed = True
        else:
            result.append(source[i])
            i += 1

    new_source = "".join(result) if changed else source

    if new_source != source:
        # Remove constr from pydantic imports if present
        new_source = re.sub(
            r"^(from pydantic import .*)\bconstr,?\s*",
            lambda m: m.group(1),
            new_source,
            flags=re.MULTILINE,
        )
        # Clean up trailing comma + whitespace before closing or end of line
        new_source = re.sub(
            r"(from pydantic import [^)\n]*?),\s*$",
            r"\1",
            new_source,
            flags=re.MULTILINE,
        )

        # Add Annotated to existing typing import, or create one
        typing_import = re.search(
            r"^from typing import (.+)$", new_source, re.MULTILINE
        )
        if typing_import:
            if "Annotated" not in typing_import.group(1):
                new_source = new_source.replace(
                    typing_import.group(0),
                    typing_import.group(0).rstrip() + ", Annotated",
                )
        else:
            new_source = _insert_imports(new_source, ["from typing import Annotated"])

        # Add StringConstraints to existing pydantic import, or create one
        pydantic_import = re.search(
            r"^from pydantic import (.+)$", new_source, re.MULTILINE
        )
        if pydantic_import:
            if "StringConstraints" not in pydantic_import.group(1):
                new_source = new_source.replace(
                    pydantic_import.group(0),
                    pydantic_import.group(0).rstrip() + ", StringConstraints",
                )
        else:
            new_source = _insert_imports(
                new_source, ["from pydantic import StringConstraints"]
            )

        count = source.count("constr(")
        log.info(
            "  Replaced %d constr() call(s) with Annotated[str, StringConstraints(...)]",
            count,
        )

    return new_source


def _apply_post_generation_fixes(source: str, schema_info: "SchemaInfo") -> str:
    """Apply schema-specific field type corrections from ``POST_GENERATION_FIELD_FIXES``.

    These fixes address known naming collisions and forward-compatibility issues
    that the generic deduplication pipeline cannot resolve automatically (e.g.,
    a class-registry entry mapping ``SchemaEmbedded`` to the wrong schema).

    Each fix is a simple substring replacement.  If the expected fragment is not
    found in the source, a warning is logged: this typically means the upstream
    schema has changed and the fix table needs updating.

    Extra imports required by the replacement types are deduplicated against
    existing imports and inserted via :func:`_insert_imports`.

    Args:
        source: Post-processed Python source text.
        schema_info: The schema being fixed (used to look up its key in the
            ``POST_GENERATION_FIELD_FIXES`` table).

    Returns:
        The source with all applicable fixes applied.
    """
    fixes = POST_GENERATION_FIELD_FIXES.get(schema_info.key, [])
    if not fixes:
        return source

    extra_imports: list[str] = []
    for cls_name, old_fragment, new_fragment, imports in fixes:
        if old_fragment in source:
            source = source.replace(old_fragment, new_fragment, 1)
            extra_imports.extend(imports)
            log.info("  Applied field fix for %s", cls_name)
        else:
            log.warning(
                "  Field fix for %s not applied (fragment not found in source). "
                "Schema may have changed.",
                cls_name,
            )

    if extra_imports:
        # Filter out imports already present to avoid duplicates
        new_imports = [imp for imp in extra_imports if imp not in source]
        if new_imports:
            source = _insert_imports(source, new_imports)

        # Remove local class definitions that are now shadowed by imports
        for imp in extra_imports:
            m = re.match(r"from\s+\S+\s+import\s+(.+)", imp)
            if m:
                for name in m.group(1).split(","):
                    name = name.strip()
                    if name and name.isidentifier():
                        block = find_class_block(source, name)
                        if block:
                            start, end = block
                            source = source[:start] + source[end:]
                            log.info("  Removed shadowed class '%s'", name)

    return source


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("generate_models")


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class SchemaInfo:
    """Metadata for a single JSON schema to generate.

    Instances are created by :func:`discover_schemas` and carry both the
    input location (``abs_path``) and derived output paths (``output_dir``,
    ``output_file``).

    Attributes:
        name: Schema directory name, e.g. ``"semanticQuery"``.
        version: Semver string, e.g. ``"1.3.0"``.
        filename: JSON file inside the version directory, e.g.
            ``"schema.json"`` or ``"schema-embedded.json"``.
        abs_path: Resolved absolute path to the JSON file on disk.
        external_refs: Raw ``$ref`` target strings parsed from the schema
            (populated by :func:`parse_external_refs`).
        depends_on: Set of schema keys (``"name/version"``) that must be
            generated before this schema.

    Computed properties:
        key: ``"name/version"`` identifier used as dict key throughout.
        module_name: Python-safe directory name (``camelCase`` → lowercase).
        version_dir: ``"v2_3_0"``-style directory name.
        output_dir: Full path to the output directory under ``OUTPUT_ROOT``.
        output_file: Full path to the generated ``model.py``.
        import_path: Dot-separated import path relative to the models root.
    """

    name: str
    version: str
    filename: str
    abs_path: Path = field(default_factory=Path)

    external_refs: list[str] = field(default_factory=list)
    depends_on: set[str] = field(default_factory=set)

    @property
    def key(self) -> str:
        return f"{self.name}/{self.version}"

    @property
    def module_name(self) -> str:
        """Python-safe module name: camelCase → lowercase."""
        return self.name.lower()

    @property
    def version_dir(self) -> str:
        """Version as directory name: '2.3.0' → 'v2_3_0'."""
        return "v" + self.version.replace(".", "_")

    @property
    def output_dir(self) -> Path:
        return OUTPUT_ROOT / self.module_name / self.version_dir

    @property
    def output_file(self) -> Path:
        return self.output_dir / "model.py"

    @property
    def import_path(self) -> str:
        """Dot-separated import path relative to models root."""
        return f"{self.module_name}.{self.version_dir}.model"


# ---------------------------------------------------------------------------
# Class registry - tracks which classes belong to which schema
# ---------------------------------------------------------------------------


@dataclass
class ClassRecord:
    """A generated Python class and its origin schema."""

    class_name: str
    schema_key: str  # which schema generated it
    import_path: str  # Python import path
    signature: str | None = None  # structural fingerprint of class block


class ClassRegistry:
    """Tracks all generated classes to detect and resolve duplicates across schemas.

    The registry is the central data structure for cross-schema deduplication.
    As each schema is generated and post-processed, its surviving classes are
    registered here.  When a later schema generates a class with the same name,
    the registry is consulted to decide whether the duplicate can be safely
    replaced with an import (see :meth:`can_substitute`).

    Registration uses **first-wins** semantics: the first schema to register a
    class name owns it.  Subsequent calls to :meth:`register` with the same
    name are silently ignored.  Hand-crafted classes are pre-registered by
    :func:`pre_register_handcrafted_classes` before any code generation begins.
    """

    def __init__(self) -> None:
        self._classes: dict[str, ClassRecord] = {}

    def register(
        self,
        class_name: str,
        schema_key: str,
        import_path: str,
        signature: str | None = None,
    ) -> None:
        """Register a class as belonging to *schema_key*.

        Uses first-wins semantics: if *class_name* is already registered the
        call is a no-op.  The optional *signature* is a SHA-1 hash of the
        normalised class body, used by :meth:`can_substitute` to verify
        structural equivalence before cross-schema substitution.
        """
        if class_name not in self._classes:
            self._classes[class_name] = ClassRecord(
                class_name,
                schema_key,
                import_path,
                signature,
            )

    def is_duplicate(self, class_name: str, current_schema_key: str) -> bool:
        """Return True if this class name was already generated by a DIFFERENT schema."""
        rec = self._classes.get(class_name)
        return rec is not None and rec.schema_key != current_schema_key

    def get_origin(self, class_name: str) -> ClassRecord | None:
        return self._classes.get(class_name)

    def can_substitute(
        self,
        class_name: str,
        current_signature: str | None,
    ) -> bool:
        """Return whether cross-schema substitution is safe for this class.

        Rules:
        - Hand-crafted classes are always substitutable (explicitly pre-registered)
        - Auto-generated classes must have matching structural signatures
        - Missing signatures default to NOT substitutable (fail-safe)
        """
        rec = self._classes.get(class_name)
        if rec is None:
            return False

        if rec.signature == "__handcrafted__":
            return True

        if rec.signature is None or current_signature is None:
            return False

        return rec.signature == current_signature

    @property
    def all_classes(self) -> dict[str, ClassRecord]:
        return dict(self._classes)


# ---------------------------------------------------------------------------
# Schema parsing & dependency discovery
# ---------------------------------------------------------------------------

# Regex to find all "$ref": "..." values in a JSON file
_REF_PATTERN = re.compile(r'"\$ref"\s*:\s*"([^"]+)"')

# Regex to match external refs (not starting with #)
_EXTERNAL_REF_PATTERN = re.compile(
    r"^\.\./\.\./(?P<schema>[^/]+)/(?P<version>[^/]+)/(?P<file>[^#]+)"
)


def parse_external_refs(schema_path: Path) -> list[str]:
    """Extract all external ``$ref`` target strings from a JSON schema file.

    Uses a regex scan (not a JSON parser) so it works even on malformed JSON.
    Internal refs (starting with ``#``) are excluded.

    Args:
        schema_path: Absolute path to a ``.json`` schema file.

    Returns:
        List of raw ``$ref`` values that point to other schema files,
        e.g. ``["../../semanticQuery/1.3.0/schema.json#/definitions/Foo"]``.
    """
    content = schema_path.read_text(encoding="utf-8")
    refs = _REF_PATTERN.findall(content)
    return [r for r in refs if not r.startswith("#")]


def resolve_dependency_key(ref: str) -> tuple[str, str, str] | None:
    """Parse an external $ref into (schema_name, version, filename).

    Example: '../../semanticQuery/1.3.0/schema.json#/definitions/Foo'
    Returns: ('semanticQuery', '1.3.0', 'schema.json')
    """
    m = _EXTERNAL_REF_PATTERN.match(ref)
    if m:
        return m.group("schema"), m.group("version"), m.group("file")
    return None


def discover_schemas(
    targets: list[tuple[str, str, str]],
    schema_root: Path,
) -> dict[str, SchemaInfo]:
    """Discover all schemas (targets + transitive dependencies) via BFS.

    Starting from *targets*, each schema file is parsed for external ``$ref``
    links.  Any referenced schema not already visited is added to the queue,
    ensuring transitive dependencies are included automatically.

    Args:
        targets: List of ``(name, version, filename)`` tuples from
            ``TARGET_SCHEMAS``.
        schema_root: Root directory containing schema subdirectories.

    Returns:
        Dict mapping ``"name/version"`` keys to populated :class:`SchemaInfo`
        instances.  Missing schema files are logged as warnings and skipped.
    """
    schemas: dict[str, SchemaInfo] = {}
    queue: deque[tuple[str, str, str]] = deque(targets)
    visited: set[str] = set()

    while queue:
        name, version, filename = queue.popleft()
        key = f"{name}/{version}"
        if key in visited:
            continue
        visited.add(key)

        abs_path = schema_root / name / version / filename
        if not abs_path.exists():
            log.warning("Schema file not found: %s", abs_path)
            continue

        info = SchemaInfo(
            name=name, version=version, filename=filename, abs_path=abs_path
        )
        info.external_refs = parse_external_refs(abs_path)

        # Resolve each external ref to a dependency schema
        for ref in info.external_refs:
            dep = resolve_dependency_key(ref)
            if dep:
                dep_name, dep_version, dep_file = dep
                dep_key = f"{dep_name}/{dep_version}"
                info.depends_on.add(dep_key)

                # If this dependency isn't already queued/visited, add it
                if dep_key not in visited:
                    queue.append((dep_name, dep_version, dep_file))

        schemas[key] = info

    return schemas


def topological_sort(schemas: dict[str, SchemaInfo]) -> list[SchemaInfo]:
    """Return schemas in dependency order (base schemas first).

    Uses Kahn's algorithm (BFS from zero-in-degree nodes).  Raises
    ``RuntimeError`` if a cycle is detected: this indicates a bug in the
    schema repository or in :func:`discover_schemas`.

    Args:
        schemas: Dict of ``"name/version"`` → :class:`SchemaInfo` as returned
            by :func:`discover_schemas`.

    Returns:
        List of :class:`SchemaInfo` in a valid generation order.

    Raises:
        RuntimeError: If the dependency graph contains a cycle.
    """
    in_degree: dict[str, int] = {k: 0 for k in schemas}
    dependents: dict[str, list[str]] = defaultdict(list)

    for key, info in schemas.items():
        for dep_key in info.depends_on:
            if dep_key in schemas:
                in_degree[key] += 1
                dependents[dep_key].append(key)

    queue: deque[str] = deque(k for k, d in in_degree.items() if d == 0)
    order: list[SchemaInfo] = []

    while queue:
        key = queue.popleft()
        order.append(schemas[key])
        for dependent in dependents[key]:
            in_degree[dependent] -= 1
            if in_degree[dependent] == 0:
                queue.append(dependent)

    if len(order) != len(schemas):
        unresolved = set(schemas.keys()) - {s.key for s in order}
        log.error("Circular dependency detected! Unresolved: %s", unresolved)
        raise RuntimeError(f"Circular dependency among: {unresolved}")

    return order


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------


MAX_RETRIES = 3


def run_codegen(schema_info: SchemaInfo) -> bool:
    """Shell out to ``datamodel-codegen`` for a single schema file.

    Creates the output directory if needed, then runs the command with
    ``CODEGEN_BASE_FLAGS``.  On failure the command is retried up to
    ``MAX_RETRIES`` times with exponential back-off (``attempt * 2`` seconds).

    Side effects:
        - Creates ``schema_info.output_dir`` on disk.
        - Writes ``schema_info.output_file`` on success.

    Args:
        schema_info: Schema to generate.

    Returns:
        ``True`` if generation succeeded, ``False`` otherwise.

    Note:
        ``ModuleNotFoundError`` and ``ImportError`` are currently classified as
        "transient" and retried, but in practice these are deterministic
        failures that will not resolve on retry.
    """
    import time

    schema_info.output_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        "datamodel-codegen",
        "--input",
        str(schema_info.abs_path),
        *CODEGEN_BASE_FLAGS,
        "--output",
        str(schema_info.output_file),
    ]

    log.info("Running: %s", " ".join(cmd))

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=False,
                timeout=120,
            )
            if result.returncode == 0:
                if result.stderr:
                    # Filter out the FutureWarning about formatters
                    important_warnings = [
                        line
                        for line in result.stderr.strip().split("\n")
                        if line.strip()
                        and "FutureWarning" not in line
                        and "code_formatter" not in line
                        and "datamodel_code_generator" not in line
                    ]
                    if important_warnings:
                        log.warning(
                            "datamodel-codegen warnings for %s:\n%s",
                            schema_info.key,
                            "\n".join(important_warnings),
                        )
                return True

            # Check if it's a transient error worth retrying
            stderr = result.stderr or ""
            is_transient = any(
                msg in stderr
                for msg in ("ModuleNotFoundError", "ImportError", "PermissionError")
            )

            if is_transient and attempt < MAX_RETRIES:
                log.warning(
                    "  Transient error on attempt %d/%d for %s, retrying in %ds...",
                    attempt,
                    MAX_RETRIES,
                    schema_info.key,
                    attempt * 2,
                )
                time.sleep(attempt * 2)
                continue

            log.error("datamodel-codegen failed for %s:\n%s", schema_info.key, stderr)
            return False

        except subprocess.TimeoutExpired:
            if attempt < MAX_RETRIES:
                log.warning(
                    "  Timeout on attempt %d/%d, retrying...", attempt, MAX_RETRIES
                )
                time.sleep(attempt * 2)
                continue
            log.error(
                "datamodel-codegen timed out for %s after %d attempts",
                schema_info.key,
                MAX_RETRIES,
            )
            return False
        except FileNotFoundError:
            log.error(
                "datamodel-codegen not found. Install with: pip install datamodel-code-generator"
            )
            return False

    return False


# ---------------------------------------------------------------------------
# Post-processing: Deduplication
# ---------------------------------------------------------------------------

# Regex patterns for parsing generated Python code
_CLASS_DEF_PATTERN = re.compile(r"^class\s+(\w+)\s*\(", re.MULTILINE)
_NUMBERED_VARIANT_PATTERN = re.compile(r"^(\w+?)(\d+)$")


def extract_class_names(python_source: str) -> list[str]:
    """Extract all class names defined in a Python source string.

    Args:
        python_source: Complete Python source text.

    Returns:
        List of class names in declaration order.
    """
    return _CLASS_DEF_PATTERN.findall(python_source)


def extract_class_signatures(python_source: str) -> dict[str, str]:
    """Extract deterministic structural signatures for each class block.

    The signature intentionally ignores class *name* and whitespace so
    identical classes generated in different schemas can be safely
    deduplicated, while similarly named classes with different structure are
    kept local.

    Normalisation steps:
        1. Replace the class name in the header with ``__CLASS__``.
        2. Strip comments (``# …``).
        3. Collapse all whitespace to a single space.
        4. SHA-1 hash the result.

    Args:
        python_source: Complete Python source text.

    Returns:
        Dict mapping class name → hex SHA-1 digest of the normalised body.
    """
    signatures: dict[str, str] = {}
    class_names = extract_class_names(python_source)

    for class_name in class_names:
        block = find_class_block(python_source, class_name)
        if not block:
            continue
        start, end = block
        class_text = python_source[start:end]

        # Normalize the header to avoid name-specific hash differences.
        normalized = re.sub(
            rf"^class\s+{re.escape(class_name)}\s*\(",
            "class __CLASS__(",
            class_text,
            count=1,
            flags=re.MULTILINE,
        )
        # Remove comments and collapse whitespace for stable hashing.
        normalized = re.sub(r"#.*$", "", normalized, flags=re.MULTILINE)
        normalized = re.sub(r"\s+", " ", normalized).strip()

        signatures[class_name] = hashlib.sha1(normalized.encode("utf-8")).hexdigest()

    return signatures


def find_class_block(source: str, class_name: str) -> tuple[int, int] | None:
    """Find the start and end character positions of a class definition block.

    The algorithm works in two phases:

    **Phase 1: Header**: Starting from the ``class Name(`` match, track
    parenthesis depth to find the closing ``):``.  Strings and comments
    inside the header are skipped to avoid miscounting brackets.

    **Phase 2: Body**: Walk subsequent lines.  Any indented or blank line
    belongs to the body.  The first non-indented, non-empty line marks the
    start of the next top-level block.

    Handles multi-line class headers like::

        class Foo(
            RootModel[Type1 | Type2]
        ):
            root: ...

    Args:
        source: Complete Python source text.
        class_name: Exact class name to locate.

    Returns:
        ``(start, end)`` character offsets, or ``None`` if not found.

    Note:
        The string/comment skipper inside Phase 1 does not handle escaped
        quotes (``\\\"``) or raw strings.  This is acceptable for
        machine-generated code.
    """
    pattern = re.compile(
        rf"^class\s+{re.escape(class_name)}\s*\(",
        re.MULTILINE,
    )
    match = pattern.search(source)
    if not match:
        return None

    start = match.start()

    # Phase 1: Find the end of the class HEADER by tracking parenthesis depth.
    # The header starts at "class Name(" and ends when we find the matching ")"
    # followed by ":".
    pos = match.end()  # position right after the opening "("
    paren_depth = 1
    header_end = None

    while pos < len(source) and paren_depth > 0:
        ch = source[pos]
        if ch == "(":
            paren_depth += 1
        elif ch == ")":
            paren_depth -= 1
            if paren_depth == 0:
                # Find the ":" after the closing ")"
                rest = source[pos : pos + 20]
                colon_offset = rest.find(":")
                if colon_offset >= 0:
                    colon_pos = pos + colon_offset + 1
                    # Advance to end of line
                    newline = source.find("\n", colon_pos)
                    header_end = (newline + 1) if newline >= 0 else len(source)
                else:
                    header_end = pos + 1
                break
        elif ch == "#":
            # Skip to end of line (comment)
            newline = source.find("\n", pos)
            pos = newline if newline >= 0 else len(source)
            continue
        elif ch in ('"', "'"):
            # Skip string literals
            quote = source[pos : pos + 3]
            if quote in ('"""', "'''"):
                end_q = source.find(quote, pos + 3)
                pos = (end_q + 3) if end_q >= 0 else len(source)
                continue
            else:
                end_q = source.find(ch, pos + 1)
                pos = (end_q + 1) if end_q >= 0 else len(source)
                continue
        pos += 1

    if header_end is None:
        # Fallback: assume single-line header
        newline = source.find("\n", start)
        header_end = (newline + 1) if newline >= 0 else len(source)

    # Phase 2: Find the end of the class BODY.
    # The body consists of all indented lines (and blank lines) following the header.
    body_end = header_end
    remaining = source[header_end:]

    for line in remaining.split("\n"):
        stripped = line.strip()
        if stripped == "":
            body_end += len(line) + 1
            continue

        # A non-indented, non-empty line marks the start of the next block
        if line and not line[0].isspace():
            break

        body_end += len(line) + 1

    return start, body_end


def identify_numbered_variants(class_names: list[str]) -> dict[str, list[str]]:
    """Identify numbered class variants like ``QueryExpressionContainer1``-``47``.

    A class is considered a numbered variant if its name matches
    ``<BaseName><Digit(s)>`` (see ``_NUMBERED_VARIANT_PATTERN``).  Only
    groups with **2 or more** variants are returned: a single ``Foo1``
    without ``Foo2`` is not treated as a variant group.

    Args:
        class_names: List of class names from :func:`extract_class_names`.

    Returns:
        Dict mapping base name → sorted list of numbered variant names.
    """
    variants: dict[str, list[str]] = defaultdict(list)
    base_classes = set(class_names)

    for name in class_names:
        m = _NUMBERED_VARIANT_PATTERN.match(name)
        if m:
            base_name = m.group(1)
            # Only group as variants if:
            # 1. There are multiple numbered versions
            # 2. The base name also exists as a class OR there are >1 numbered versions
            variants[base_name].append(name)

    # Filter: only keep groups with 2+ variants
    return {k: sorted(v) for k, v in variants.items() if len(v) >= 2}


def _check_rootmodel_self_reference(
    source: str, base_name: str, variants: list[str]
) -> bool:
    """Check if merging variants would create a self-referential RootModel.

    Example:
        class VisualContainer(RootModel[VisualContainer1 | VisualContainer2]):
            root: VisualContainer1 | VisualContainer2

    If we merge VisualContainer1 and VisualContainer2 into VisualContainer,
    we'd get:
        class VisualContainer(RootModel[VisualContainer]):  # Self-reference!
            root: VisualContainer

    This function detects such cases by looking for a class named `base_name`
    that inherits from RootModel and references the variants.
    """
    # Look for a RootModel class with the base name that references the variants
    rootmodel_pattern = re.compile(
        rf"class\s+{re.escape(base_name)}\s*\(\s*RootModel\s*\[",
        re.MULTILINE,
    )
    match = rootmodel_pattern.search(source)
    if not match:
        return False

    # Found a RootModel class - check if it references the variants
    # Get the content after the match to find the type parameter
    start = match.end()
    bracket_depth = 1
    pos = start
    while pos < len(source) and bracket_depth > 0:
        if source[pos] == "[":
            bracket_depth += 1
        elif source[pos] == "]":
            bracket_depth -= 1
        pos += 1

    type_param = source[start : pos - 1]

    # Check if the type parameter contains any of the variants
    for variant in variants:
        if re.search(rf"\b{re.escape(variant)}\b", type_param):
            return True

    return False


def deduplicate_against_registry(
    source: str,
    schema_info: SchemaInfo,
    registry: ClassRegistry,
    schemas: dict[str, SchemaInfo],
) -> str:
    """Remove duplicate classes and replace with imports from the original schema.

    For each class defined in *source*, check if the :class:`ClassRegistry`
    already has it registered from a different schema.  If so: and if the
    structural signatures match (see :meth:`ClassRegistry.can_substitute`):
    the local class definition is removed and replaced with an import from
    the origin schema's module.

    Hand-crafted classes are imported via a wildcard import from
    ``expressions``; auto-generated classes get explicit ``from …
    import …`` statements built by :func:`_build_relative_import`.

    Args:
        source: Post-processed Python source text for the current schema.
        schema_info: The schema currently being processed.
        registry: Global class registry populated by previously generated
            schemas.
        schemas: Full schema dict (needed to resolve origin import paths).

    Returns:
        The source with duplicate class definitions removed and import
        statements added.

    Note:
        Class blocks are removed one at a time, mutating the source string
        between removals.  See "Known Issues" in the module docstring.
    """
    class_names = extract_class_names(source)
    class_signatures = extract_class_signatures(source)
    duplicates: dict[str, ClassRecord] = {}

    for cls_name in class_names:
        if registry.is_duplicate(cls_name, schema_info.key):
            origin = registry.get_origin(cls_name)
            if origin:
                current_sig = class_signatures.get(cls_name)
                if registry.can_substitute(cls_name, current_sig):
                    duplicates[cls_name] = origin
                else:
                    log.warning(
                        "  Keeping local class '%s' (signature mismatch with %s)",
                        cls_name,
                        origin.schema_key,
                    )

    if not duplicates:
        return source

    log.info("  Found %d duplicate classes to replace with imports", len(duplicates))

    # Group duplicates by origin module for clean import statements
    imports_by_module: dict[str, list[str]] = defaultdict(list)
    handcrafted_classes: list[str] = []

    for cls_name, record in duplicates.items():
        # Check if this is a hand-crafted class
        if cls_name in HANDCRAFTED_CLASSES:
            handcrafted_classes.append(cls_name)
            continue

        # Build relative import path for auto-generated classes
        origin_schema = schemas.get(record.schema_key)
        if origin_schema:
            # Calculate relative import from current schema's module to origin
            rel_import = _build_relative_import(schema_info, origin_schema)
            imports_by_module[rel_import].append(cls_name)

    # Remove duplicate class definitions from source
    for cls_name in duplicates:
        block = find_class_block(source, cls_name)
        if block:
            start, end = block
            source = source[:start] + source[end:]

    # Build import statements
    import_lines: list[str] = []

    # Add import for hand-crafted classes (explicit names, not wildcard)
    if handcrafted_classes:
        classes_str = ", ".join(sorted(handcrafted_classes))
        import_lines.append(f"from ...semanticquery.expressions import {classes_str}")
        log.info(
            "    Added hand-crafted import for %d classes", len(handcrafted_classes)
        )

    # Add imports for auto-generated classes from other schemas
    for module_path, class_list in sorted(imports_by_module.items()):
        classes_str = ", ".join(sorted(class_list))
        import_lines.append(f"from {module_path} import {classes_str}")

    if import_lines:
        source = _insert_imports(source, import_lines)

    return source


def _extract_imported_names(source: str) -> set[str]:
    """Extract class/symbol names that are imported (not locally defined).

    Parses ``from … import …`` statements via regex.  Handles comma-separated
    names and ``as`` aliases (returns the alias).  Does **not** handle
    wildcard imports: those are checked separately via ``HANDCRAFTED_CLASSES``.

    Args:
        source: Python source text.

    Returns:
        Set of imported symbol names.
    """
    imported: set[str] = set()
    for m in re.finditer(r"^from\s+\S+\s+import\s+(.+)$", source, re.MULTILINE):
        names = m.group(1)
        for name in names.split(","):
            name = name.strip().split(" as ")[-1].strip()
            if name and name.isidentifier():
                imported.add(name)
    return imported


def _remove_unused_imports(source: str) -> str:
    """Remove imported names that are not referenced in the rest of the file.

    After deduplication replaces local class definitions with imports, some
    of those imported names may not actually be used anywhere in the file
    (e.g., the class was defined but never referenced as a field type).
    This function removes those unused names from import statements.

    Wildcard imports (``from … import *``) are left untouched.

    Args:
        source: Python source text.

    Returns:
        The source with unused import names removed.
    """
    lines = source.split("\n")
    import_pattern = re.compile(r"^from\s+(\S+)\s+import\s+(.+)$")
    output_lines: list[str] = []

    for line in lines:
        m = import_pattern.match(line)
        if not m or "*" in m.group(2):
            output_lines.append(line)
            continue

        module = m.group(1)
        raw_names = [n.strip() for n in m.group(2).split(",") if n.strip()]

        # Check each name: is it referenced outside of import lines?
        # Build a version of source without any import lines to search in
        used_names: list[str] = []
        for name in raw_names:
            # Get the actual name (handle "X as Y" aliases)
            local_name = name.split(" as ")[-1].strip()
            # Check if the name appears anywhere in the file outside this import
            # Use word-boundary search in non-import lines
            pattern = re.compile(rf"\b{re.escape(local_name)}\b")
            found = False
            for other_line in lines:
                if other_line == line:
                    continue
                # Skip other import lines when checking for usage
                if import_pattern.match(other_line):
                    continue
                if pattern.search(other_line):
                    found = True
                    break
            if found:
                used_names.append(name)

        if used_names:
            names_str = ", ".join(used_names)
            output_lines.append(f"from {module} import {names_str}")
        # else: drop the entire import line

    return "\n".join(output_lines)


def _remove_stale_rebuild_calls(source: str) -> str:
    """Remove ``.model_rebuild()`` calls for classes not defined in the file.

    After deduplication removes class definitions (replacing them with imports),
    the corresponding ``ClassName.model_rebuild()`` calls become stale: they
    are unnecessary for imported classes.  This function removes them.

    Args:
        source: Python source text.

    Returns:
        The source with stale ``.model_rebuild()`` calls removed.
    """
    defined_classes = set(extract_class_names(source))
    lines = source.split("\n")
    output_lines: list[str] = []

    rebuild_pattern = re.compile(r"^(\w+)\.model_rebuild\(\)$")

    for line in lines:
        m = rebuild_pattern.match(line.strip())
        if m:
            class_name = m.group(1)
            if class_name not in defined_classes:
                continue  # Skip rebuild for non-local class
        output_lines.append(line)

    return "\n".join(output_lines)


def merge_numbered_variants(source: str) -> str:
    """Merge numbered class variants (e.g., ``Foo1``-``Foo47``) into a single base class.

    When ``datamodel-codegen`` encounters a schema with *N* optional fields and
    an "exactly one required" constraint, it generates *N* separate classes,
    each making a different field required.  This function collapses them:

    1. Identify numbered variant groups via :func:`identify_numbered_variants`.
    2. If the base class already exists (defined locally or imported), remove
       the variants and keep the base.
    3. If the base class does **not** exist, promote the first variant to act
       as the base via :func:`_promote_variant_to_base` (making all its
       required fields optional).
    4. A special case handles ``RootModel`` wrappers that would become
       self-referential after the merge: the wrapper is removed and the
       first variant is promoted instead.
    5. Replace **all** references to variant names with the base name.
    6. Clean up resulting duplicate union members, list items, and
       ``model_rebuild()`` calls.

    Args:
        source: Python source text (after deduplication).

    Returns:
        The source with all numbered variant groups collapsed.

    Note:
        The global ``re.sub`` in step 5 replaces variant names everywhere in
        the file, including inside string literals and ``description=`` Field
        arguments.  See "Known Issues" in the module docstring.
    """
    class_names = extract_class_names(source)
    variant_groups = identify_numbered_variants(class_names)

    if not variant_groups:
        return source

    # Also consider imported classes as "available" - this handles the case where
    # the base class was already generated in a dependency schema and imported.
    imported_names = _extract_imported_names(source)

    # Check for wildcard imports from expressions which imports all hand-crafted classes
    has_handcrafted_import = "from ...semanticquery.expressions import *" in source

    # Combine available names: local classes + imported names + hand-crafted (if imported)
    available_names = set(class_names) | imported_names
    if has_handcrafted_import:
        available_names |= HANDCRAFTED_CLASSES

    for base_name, variants in variant_groups.items():
        # Check if merging would create a self-referential RootModel
        # e.g., class VisualContainer(RootModel[VisualContainer1|VisualContainer2])
        # would become class VisualContainer(RootModel[VisualContainer])
        would_create_self_reference = _check_rootmodel_self_reference(
            source, base_name, variants
        )

        if would_create_self_reference:
            log.info(
                "  Merging %d numbered variants of '%s' with RootModel collapse (%s...%s)",
                len(variants),
                base_name,
                variants[0],
                variants[-1],
            )
            # Remove the RootModel wrapper class first
            rootmodel_block = find_class_block(source, base_name)
            if rootmodel_block:
                start, end = rootmodel_block
                source = source[:start] + source[end:]

            # Promote the first variant to the base name, making all fields optional
            source = _promote_variant_to_base(source, base_name, variants)
        else:
            log.info(
                "  Merging %d numbered variants of '%s' (%s...%s)",
                len(variants),
                base_name,
                variants[0],
                variants[-1],
            )

            base_available = base_name in available_names

            if base_available:
                # Base class exists (defined locally or imported) - just remove variants
                for variant in variants:
                    block = find_class_block(source, variant)
                    if block:
                        start, end = block
                        source = source[:start] + source[end:]
            else:
                # Base class not available - promote first variant to be the base class
                source = _promote_variant_to_base(source, base_name, variants)

        # Replace ALL references to numbered variants with the base class name
        for variant in variants:
            source = re.sub(
                rf"\b{re.escape(variant)}\b",
                base_name,
                source,
            )

    # Clean up: remove duplicate union members that result from the renaming
    source = _deduplicate_union_members(source)

    # Clean up: remove duplicate items in lists
    source = _deduplicate_list_items(source)

    # Clean up: remove duplicate model_rebuild() calls
    source = _deduplicate_rebuild_calls(source)

    # Remove any resulting blank lines clusters (more than 2 consecutive)
    source = re.sub(r"\n{4,}", "\n\n\n", source)

    return source


def _make_fields_optional(class_text: str) -> str:
    """Make all required fields in a class definition optional.

    Handles multi-line type annotations (``Literal[...]``, ``constr(…)``,
    ``Field(…)``) by tracking bracket depth to find where each field
    definition ends before processing it.

    For each required field (no ``None`` in type, no ``None`` default):

    1. Add ``| None`` after the type annotation.
    2. Change ``Field(…)`` to ``Field(None, …)`` or add ``= None`` if there
       is no ``Field()`` call.

    Args:
        class_text: The text of a single class definition (header + body).

    Returns:
        The class text with all required fields converted to optional.

    Note:
        The "already optional" check uses ``"None" in full_field`` which is a
        substring match.  This could mis-fire on identifiers that contain
        "None" as a substring (e.g., ``isNoneValue``).
    """
    lines = class_text.split("\n")
    result_lines: list[str] = []

    # Skip lines that are not field definitions (class header, model_config, etc.)
    # Field definitions start with: <indent><identifier>: <type>
    _FIELD_START = re.compile(r"^([ \t]+)(\w+):\s*(.*)$")
    # Lines that are NOT field starts (class def, model_config, decorators, etc.)
    _SKIP_PATTERNS = re.compile(r"^\s*(class\s|model_config\s*=|#|\)|extra\s*=|@|\s*$)")

    i = 0
    while i < len(lines):
        line = lines[i]
        m = _FIELD_START.match(line)

        # Skip non-field lines
        if not m or _SKIP_PATTERNS.match(line):
            result_lines.append(line)
            i += 1
            continue

        # Found a field definition start. Collect the full definition
        # (may span multiple lines due to multi-line Field() or Literal[])
        field_lines = [line]
        # Track bracket depth to find where this field definition ends
        depth = 0
        for ch in line:
            if ch in "([":
                depth += 1
            elif ch in ")]":
                depth -= 1

        j = i + 1
        while depth > 0 and j < len(lines):
            field_lines.append(lines[j])
            for ch in lines[j]:
                if ch in "([":
                    depth += 1
                elif ch in ")]":
                    depth -= 1
            j += 1

        full_field = "\n".join(field_lines)

        # Check if already optional
        indent = m.group(1)
        fname = m.group(2)
        type_and_rest = m.group(3)

        if "None" in full_field or "Optional" in full_field:
            # Already optional - keep as-is
            result_lines.extend(field_lines)
            i = j
            continue

        # Find the type annotation before any = or Field(
        # The type is everything between "field_name: " and " = " or end of first line
        # For multi-line types, we need to find where the type ends
        if "= Field(" in full_field:
            # Type is before "= Field("
            field_idx = full_field.index("= Field(")
            # Find the colon position (after field name)
            colon_pos = full_field.index(":", len(indent) + len(fname))
            type_str = full_field[colon_pos + 1 : field_idx].strip()

            # Add | None to type and change Field(...) to Field(None, ...)
            rest = full_field[field_idx:].replace("= Field(", "= Field(None, ", 1)
            # Remove the "..." sentinel (may be on separate line with whitespace)
            rest = re.sub(r"Field\(None,\s*\.\.\.\s*,", "Field(None,", rest)
            rest = re.sub(r"Field\(None,\s*\.\.\.\s*\)", "Field(None)", rest)
            new_field = full_field[: colon_pos + 1] + " " + type_str + " | None" + rest
            result_lines.extend(new_field.split("\n"))
        elif "=" not in type_and_rest:
            # Simple type with no default: "field_name: SomeType"
            result_lines.append(
                f"{indent}{fname}: {type_and_rest.rstrip()} | None = None"
            )
            # Add any continuation lines (shouldn't happen for simple types)
            result_lines.extend(field_lines[1:])
        else:
            # Has some default but no Field() - rare case, just keep as-is
            result_lines.extend(field_lines)

        i = j

    return "\n".join(result_lines)


def _promote_variant_to_base(source: str, base_name: str, variants: list[str]) -> str:
    """Promote the first variant to act as the base class, then remove the rest.

    Instead of merging fields from all variants (which breaks on multi-line
    ``Field()`` definitions), we take the *entire* first variant class block,
    rename it to *base_name*, and make all its required fields optional via
    :func:`_make_fields_optional`.

    If the first variant's block cannot be found (e.g., already removed by a
    prior step), a fallback path simply removes all variant blocks.

    Args:
        source: Python source text.
        base_name: The desired class name (without trailing digits).
        variants: Sorted list of numbered variant names (e.g.,
            ``["Foo1", "Foo2", …]``).

    Returns:
        The source with the first variant renamed and the rest removed.
    """
    # Get the first variant's complete class block
    first_block = find_class_block(source, variants[0])
    if not first_block:
        # Fallback: just remove all variants
        for variant in variants:
            block = find_class_block(source, variant)
            if block:
                start, end = block
                source = source[:start] + source[end:]
        return source

    start, end = first_block
    class_text = source[start:end]

    # Rename the class
    class_text = re.sub(
        rf"class\s+{re.escape(variants[0])}\s*\(",
        f"class {base_name}(",
        class_text,
        count=1,
    )

    # Make required fields optional by processing complete field definitions.
    # A field definition starts with "    field_name: Type..." and may span
    # multiple lines (e.g., Literal['long-url'], constr(max_length=50),
    # or multi-line Field(...) calls).
    class_text = _make_fields_optional(class_text)

    # Replace the first variant block with the renamed/modified class
    source = source[:start] + class_text + source[end:]

    # Remove remaining variant class definitions (skip the first, already replaced)
    for variant in variants[1:]:
        block = find_class_block(source, variant)
        if block:
            s, e = block
            source = source[:s] + source[e:]

    return source


def _deduplicate_union_members(source: str) -> str:
    """Remove duplicate members in union type annotations.

    After variant renaming, unions like
    ``QueryExpressionContainer | QueryExpressionContainer | …`` need to be
    collapsed to a single ``QueryExpressionContainer``.

    Three passes are applied:

    1. **Parenthesised unions**: ``(A | B | A)`` → ``A | B``.
    2. **Simple inline unions** after ``:``: ``field: A | A`` → ``field: A``.
    3. **Unions inside ``list[…]``**: ``list[A | A]`` → ``list[A]``.

    Args:
        source: Python source text (after variant renaming).

    Returns:
        The source with duplicate union members removed.
    """

    def _dedup_union_str(union_str: str) -> str:
        """Deduplicate a union string, preserving order."""
        # Normalize whitespace - collapse multiple spaces/newlines
        normalized = re.sub(r"\s+", " ", union_str)
        # Split by | and deduplicate
        members = [m.strip() for m in normalized.split("|")]
        seen: set[str] = set()
        unique: list[str] = []
        for member in members:
            if member and member not in seen:
                seen.add(member)
                unique.append(member)
        return " | ".join(unique)

    # First pass: Handle multi-line union types in parentheses
    # Pattern: (Type1\n| Type2\n| Type3...) or (list[Type1\n| Type2...])
    def _process_paren_block(match: re.Match) -> str:
        content = match.group(1)
        # Check if this contains union operators
        if "|" not in content:
            return match.group(0)
        # Deduplicate the union
        deduped = _dedup_union_str(content)
        # If result is simple enough, remove parentheses
        if "\n" not in deduped and len(deduped) < 100:
            return deduped
        return f"({deduped})"

    # Match parenthesized type annotations that might span multiple lines
    source = re.sub(
        r"\(\s*([\w\[\], \n\t|]+)\s*\)",
        _process_paren_block,
        source,
        flags=re.DOTALL,
    )

    # Second pass: Handle single-line union types after ":"
    def _dedup_simple_union(match: re.Match) -> str:
        return _dedup_union_str(match.group(0))

    source = re.sub(
        r"(?<=:\s)[\w\[\], ]+(?:\s*\|\s*[\w\[\], ]+)+",
        _dedup_simple_union,
        source,
    )

    # Third pass: Handle union types inside list[] brackets (including multi-line)
    def _dedup_list_union(match: re.Match) -> str:
        content = match.group(1)
        if "|" not in content:
            return match.group(0)
        deduped = _dedup_union_str(content)
        return f"list[{deduped}]"

    # Match list[...] with potential multi-line union content
    source = re.sub(
        r"list\[([\w\[\], \n\t|]+)\]",
        _dedup_list_union,
        source,
        flags=re.DOTALL,
    )

    return source


def _deduplicate_list_items(source: str) -> str:
    """Remove duplicate items in list literals like ``[Type, Type, Type]`` → ``[Type]``.

    Args:
        source: Python source text.

    Returns:
        The source with duplicate list items collapsed.

    Note:
        The regex ``\\[([^\\[\\]]+)\\]`` matches **any** non-nested bracketed
        content, not just type annotations.  It could corrupt list
        comprehensions or string literals in arbitrary Python, but is safe
        for ``datamodel-codegen`` output.
    """

    def _dedup_list(match: re.Match) -> str:
        inner = match.group(1)
        items = [item.strip() for item in inner.split(",") if item.strip()]
        seen: set[str] = set()
        unique: list[str] = []
        for item in items:
            if item not in seen:
                seen.add(item)
                unique.append(item)
        return "[" + ", ".join(unique) + "]"

    source = re.sub(r"\[([^\[\]]+)\]", _dedup_list, source)
    return source


def _deduplicate_rebuild_calls(source: str) -> str:
    """Remove duplicate ``X.model_rebuild()`` calls.

    After variant renaming, multiple identical ``model_rebuild()`` calls may
    exist (one per original variant).  This keeps only the first occurrence
    of each.

    Args:
        source: Python source text.

    Returns:
        The source with duplicate ``model_rebuild()`` calls removed.
    """
    lines = source.split("\n")
    seen_rebuilds: set[str] = set()
    output_lines: list[str] = []

    for line in lines:
        stripped = line.strip()
        if stripped.endswith(".model_rebuild()"):
            if stripped in seen_rebuilds:
                continue  # Skip duplicate
            seen_rebuilds.add(stripped)
        output_lines.append(line)

    return "\n".join(output_lines)


def _build_relative_import(
    current_schema: SchemaInfo,
    origin_schema: SchemaInfo,
) -> str:
    """Build a Python relative import path from current schema to origin schema.

    Both modules live under ``src/pybi/report/models/{schema_name}/{version}/model.py``.
    The relative import goes up 2 levels (version → schema → models root) then
    down into the origin module.

    Example::

        filterconfiguration.v1_2_0.model → semanticquery.v1_3_0.model
        ⇒ "...semanticquery.v1_3_0.model"

    Args:
        current_schema: The schema whose ``model.py`` contains the import.
        origin_schema: The schema that originally defined the class.

    Returns:
        A relative import string like ``"...semanticquery.v1_3_0.model"``.

    Note:
        The three-dot prefix (``...``) is hardcoded and assumes both schemas
        are always at the same directory depth.
    """
    # We go up 2 levels from current: version_dir → schema_name → models root
    # Then down into origin: schema_name → version_dir → model
    return f"...{origin_schema.module_name}.{origin_schema.version_dir}.model"


def _insert_imports(source: str, import_lines: list[str]) -> str:
    """Insert import statements after the existing import block.

    Scans for the last ``from …`` / ``import …`` line (including
    ``from __future__``) and inserts the new imports immediately after it,
    separated by a comment banner.

    Args:
        source: Python source text.
        import_lines: List of import statements to insert (without newlines).

    Returns:
        The source with the new imports inserted.

    Note:
        The "last import line" heuristic does not distinguish top-level
        imports from imports inside class bodies or string literals.  Safe
        for ``datamodel-codegen`` output which has a flat structure.
    """
    lines = source.split("\n")
    last_import_idx = 0

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith(("from ", "import ")) and not stripped.startswith(
            "from __future__"
        ):
            last_import_idx = i
        elif stripped.startswith("from __future__"):
            last_import_idx = i

    # Insert after the last import line
    insert_idx = last_import_idx + 1

    # Add a blank line before our imports for clarity
    import_block = ["", "# --- Imports from dependency schemas (auto-generated) ---"]
    import_block.extend(import_lines)
    import_block.append("")

    lines[insert_idx:insert_idx] = import_block
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Hand-crafted model integration
# ---------------------------------------------------------------------------


def remove_handcrafted_classes(source: str, schema_info: SchemaInfo) -> str:
    """Remove hand-crafted classes and their variants from generated source.

    For the ``semanticQuery`` schema, a curated set of classes (listed in
    ``HANDCRAFTED_CLASSES``) has hand-crafted implementations in
    ``expressions.py``.  This function:

    1. Removes the auto-generated class definition for each hand-crafted class.
    2. Removes all ``QueryExpressionContainer`` numbered variants
       (``QueryExpressionContainer1``, ``QueryExpressionContainer2``, etc.).
    3. Replaces references to numbered variants with the base class name.
    4. Cleans up resulting duplicate union members, list items, and
       ``model_rebuild()`` calls.
    5. Adds ``HANDCRAFTED_IMPORT`` (wildcard import) for ``semanticQuery``
       schemas only.

    Args:
        source: Generated Python source text.
        schema_info: The schema being processed (used to decide whether to
            add the hand-crafted import).

    Returns:
        The source with hand-crafted class definitions removed.
    """
    class_names = extract_class_names(source)
    classes_to_remove: list[str] = []

    for cls_name in class_names:
        # Check if it's a hand-crafted class
        if cls_name in HANDCRAFTED_CLASSES:
            classes_to_remove.append(cls_name)
        # Check if it's a QueryExpressionContainer numbered variant
        elif _QUERY_EXPR_CONTAINER_VARIANT.match(cls_name):
            classes_to_remove.append(cls_name)

    if not classes_to_remove:
        return source

    log.info("  Removing %d hand-crafted/variant classes", len(classes_to_remove))

    # Remove each class definition
    for cls_name in classes_to_remove:
        block = find_class_block(source, cls_name)
        if block:
            start, end = block
            source = source[:start] + source[end:]

    # Replace all references to numbered variants with QueryExpressionContainer
    for cls_name in classes_to_remove:
        if _QUERY_EXPR_CONTAINER_VARIANT.match(cls_name):
            source = re.sub(
                rf"\b{re.escape(cls_name)}\b",
                "QueryExpressionContainer",
                source,
            )

    # Clean up: remove duplicate union members
    source = _deduplicate_union_members(source)
    source = _deduplicate_list_items(source)
    source = _deduplicate_rebuild_calls(source)

    # Add explicit import for hand-crafted classes (only for semanticQuery schema)
    if schema_info.name == "semanticQuery":
        handcrafted_names = sorted(
            cls for cls in classes_to_remove if cls in HANDCRAFTED_CLASSES
        )
        if handcrafted_names:
            classes_str = ", ".join(handcrafted_names)
            source = _insert_imports(
                source, [f"from ..expressions import {classes_str}"]
            )

    # Remove any resulting blank line clusters
    source = re.sub(r"\n{4,}", "\n\n\n", source)

    return source


def pre_register_handcrafted_classes(registry: ClassRegistry) -> None:
    """Pre-register hand-crafted classes so downstream schemas import them.

    All classes in ``HANDCRAFTED_CLASSES`` are registered under the
    ``semanticQuery/1.3.0`` schema key with a sentinel signature
    (``"__handcrafted__"``).  This ensures that when any downstream schema
    generates the same class, :meth:`ClassRegistry.can_substitute` returns
    ``True`` and the duplicate is replaced with an import.

    Note:
        The schema key ``"semanticQuery/1.3.0"`` is hardcoded because the
        hand-crafted ``expressions.py`` module lives alongside the
        1.3.0 generated models and is shared across all versions.
    """
    # Register all hand-crafted classes as belonging to semanticQuery
    import_path = "semanticquery.expressions"
    schema_key = "semanticQuery/1.3.0"

    for cls_name in HANDCRAFTED_CLASSES:
        registry.register(
            cls_name,
            schema_key,
            import_path,
            signature="__handcrafted__",
        )

    log.info("  Pre-registered %d hand-crafted classes", len(HANDCRAFTED_CLASSES))


# ---------------------------------------------------------------------------
# Init file generation
# ---------------------------------------------------------------------------


def create_init_files(schema_info: SchemaInfo) -> None:
    """Create ``__init__.py`` files for the versioned module structure.

    Two files are written:

    - **Version-level** (``{schema}/{version}/__init__.py``): re-exports
      everything from ``model.py``.
    - **Schema-level** (``{schema}/__init__.py``): re-exports from the
      version directory.  For ``semanticQuery``, also re-exports from
      ``expressions``.

    Note:
        When multiple versions of the same schema are generated, the
        schema-level ``__init__.py`` is overwritten each time, so only the
        **last version processed** ends up re-exported (last-version-wins).
    """
    version_init = schema_info.output_dir / "__init__.py"
    version_init.write_text(
        f'"""Generated models for {schema_info.name} version {schema_info.version}."""\n'
        f"from .model import *\n",
        encoding="utf-8",
    )

    schema_init = OUTPUT_ROOT / schema_info.module_name / "__init__.py"

    # Special handling for semanticQuery: also export hand-crafted expressions
    if schema_info.name == "semanticQuery":
        schema_init.write_text(
            f'"""SemanticQuery models package.\n'
            f"\n"
            f"This package provides Pydantic V2 models for Power BI semantic query structures,\n"
            f"including the hand-crafted QueryExpressionContainer that handles ~47 expression types.\n"
            f'"""\n'
            f"\n"
            f"# Export the hand-crafted expression container (always available)\n"
            f"from .expressions import *  # noqa: F401, F403\n"
            f"\n"
            f"# Export generated models\n"
            f"from .{schema_info.version_dir}.model import *  # noqa: F401, F403\n",
            encoding="utf-8",
        )
    else:
        schema_init.write_text(
            f'"""Models for {schema_info.name} - latest version: {schema_info.version}."""\n'
            f"from .{schema_info.version_dir}.model import *\n",
            encoding="utf-8",
        )


def ensure_handcrafted_helper_files(schema_info: SchemaInfo) -> None:
    """Recreate hand-crafted helper modules that generated code imports.

    Currently only applies to ``visualConfiguration/2.2.0``, which needs a
    ``general_item.py`` helper defining ``VisualContainerGeneralItem`` and
    ``VisualContainerGeneralFormattingObjects``.  These types resolve a
    class-name collision where the generic dedup would map
    ``VisualContainerFormattingObjects.general`` to the wrong ``GeneralItem``
    from ``filterconfiguration``.

    This file lives under the generated version folder and is deleted by
    ``--clean``, so it is recreated deterministically here.

    Args:
        schema_info: The schema just generated.  The function is a no-op for
            any schema other than ``visualConfiguration/2.2.0``.
    """
    if schema_info.key != "visualConfiguration/2.2.0":
        return

    helper_path = schema_info.output_dir / "general_item.py"
    helper_path.write_text(
        "\n".join(
            [
                "from __future__ import annotations",
                "",
                "from pydantic import BaseModel, ConfigDict, Field",
                "",
                "from ...formattingobjectdefinitions.v1_4_0.model import Selector",
                "",
                "",
                "class VisualContainerGeneralFormattingObjects(BaseModel):",
                "    model_config = ConfigDict(",
                '        extra="forbid",',
                "    )",
                "    x: object | None = None",
                "    y: object | None = None",
                "    width: object | None = None",
                "    height: object | None = None",
                "    altText: object | None = None",
                "    allowBinnedLineSample: object | None = None",
                "    allowOverlappingPointsSample: object | None = None",
                "    keepLayerOrder: object | None = None",
                "",
                "",
                "class VisualContainerGeneralItem(BaseModel):",
                "    model_config = ConfigDict(",
                '        extra="forbid",',
                "    )",
                "    selector: Selector | None = None",
                "    properties: VisualContainerGeneralFormattingObjects = Field(",
                "        ...,",
                '        description="Describes the properties of the object to apply formatting changes to.",',
                "    )",
                "",
            ]
        ),
        encoding="utf-8",
    )


def create_top_level_init(schemas: list[SchemaInfo]) -> None:
    """Create the top-level ``models/__init__.py`` listing all generated schemas.

    The file contains commented-out imports for each schema/version pair
    (for reference) and an empty ``__all__`` list.

    If the file already exists and does **not** contain the ``"auto-generated"``
    marker, it is assumed to have custom content and is left untouched.

    Args:
        schemas: List of successfully generated :class:`SchemaInfo` instances.
    """
    lines = [
        '"""Power BI Report Data Models - auto-generated from JSON schemas.',
        "",
        "Do not edit manually. Regenerate with: python scripts/generate_models.py",
        '"""',
        "",
    ]

    all_exports: list[str] = []

    for schema_info in schemas:
        module = f".{schema_info.module_name}.{schema_info.version_dir}.model"
        lines.append(f"# {schema_info.name} v{schema_info.version}")
        lines.append(f"# from {module} import *  # noqa: F401")
        lines.append("")

    lines.append("")
    lines.append("__all__: list[str] = []  # Populate as needed")
    lines.append("")

    init_path = OUTPUT_ROOT / "__init__.py"
    # Don't overwrite if it already exists and has custom content
    if init_path.exists():
        existing = init_path.read_text(encoding="utf-8")
        if "auto-generated" not in existing:
            log.info("Skipping top-level __init__.py (has custom content)")
            return

    init_path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------


def generate_all(
    schema_root: Path,
    targets: list[tuple[str, str, str]],
    dry_run: bool = False,
    clean: bool = False,
    incremental: bool = False,
) -> bool:
    """Main entry point: discover, generate, post-process, and organise.

    Orchestrates the full pipeline described in the module docstring.
    Each schema is processed sequentially in dependency order.  Failures
    are logged but do not abort the run: subsequent schemas continue.

    Args:
        schema_root: Root directory containing schema subdirectories.
        targets: List of ``(name, version, filename)`` tuples.
        dry_run: If ``True``, print the generation plan and exit.
        clean: If ``True``, remove existing output directories before
            regenerating.
        incremental: If ``True``, skip schemas whose ``model.py`` already
            exists.  Skipped schemas still populate the class registry so
            downstream deduplication works correctly.

    Returns:
        ``True`` if all schemas generated successfully, ``False`` if any
        failed.
    """

    log.info("=" * 70)
    log.info("Power BI Report Data Model Generation")
    log.info("=" * 70)
    log.info("Schema root : %s", schema_root)
    log.info("Output root : %s", OUTPUT_ROOT)
    log.info("")

    # Phase 1: Discover all schemas and dependencies
    log.info("[Phase 1] Discovering schemas and dependencies...")
    schemas = discover_schemas(targets, schema_root)
    log.info("  Found %d schemas (including transitive dependencies)", len(schemas))

    for key, info in schemas.items():
        deps = ", ".join(info.depends_on) if info.depends_on else "(none)"
        log.info("  %s → depends on: %s", key, deps)

    # Phase 2: Compute generation order
    log.info("")
    log.info("[Phase 2] Computing generation order (topological sort)...")
    ordered = topological_sort(schemas)
    log.info("  Generation order:")
    for i, s in enumerate(ordered, 1):
        log.info("    %d. %s (%s)", i, s.key, s.filename)

    if dry_run:
        log.info("")
        log.info("[DRY RUN] Would generate %d schemas. Exiting.", len(ordered))
        return True

    # Phase 3: Clean output if requested
    if clean:
        log.info("")
        log.info("[Phase 3] Cleaning output directory...")
        for s in ordered:
            if s.output_dir.exists():
                shutil.rmtree(s.output_dir)
                log.info("  Removed: %s", s.output_dir)

    if incremental and clean:
        log.warning(
            "--clean and --incremental were both set; --clean runs first so "
            "--incremental will have nothing to skip (full regeneration)."
        )

    # Phase 4: Generate models in dependency order
    log.info("")
    log.info("[Phase 4] Generating models...")
    registry = ClassRegistry()
    generated: list[SchemaInfo] = []
    skipped: list[SchemaInfo] = []
    failed: list[SchemaInfo] = []

    # Pre-register hand-crafted classes so downstream schemas will import them
    log.info("")
    log.info("  Pre-registering hand-crafted classes...")
    pre_register_handcrafted_classes(registry)

    for i, schema_info in enumerate(ordered, 1):
        log.info("")
        log.info(
            "[%d/%d] Generating %s v%s...",
            i,
            len(ordered),
            schema_info.name,
            schema_info.version,
        )

        # Incremental mode: skip schemas whose model.py already exists,
        # but still populate the registry from the existing file so that
        # downstream deduplication against this schema works correctly.
        if incremental and schema_info.output_file.exists():
            existing_source = schema_info.output_file.read_text(encoding="utf-8")
            existing_lines = existing_source.count("\n")
            log.info("  Skipping (already exists): %d lines", existing_lines)
            existing_classes = extract_class_names(existing_source)
            existing_signatures = extract_class_signatures(existing_source)
            for cls_name in existing_classes:
                registry.register(
                    cls_name,
                    schema_info.key,
                    schema_info.import_path,
                    signature=existing_signatures.get(cls_name),
                )
            create_init_files(schema_info)
            ensure_handcrafted_helper_files(schema_info)
            skipped.append(schema_info)
            continue

        # 4a: Run datamodel-codegen
        if not run_codegen(schema_info):
            log.error("  FAILED: Skipping post-processing for %s", schema_info.key)
            failed.append(schema_info)
            continue

        # Read generated source
        source = schema_info.output_file.read_text(encoding="utf-8")
        original_lines = source.count("\n")
        log.info("  Generated: %d lines", original_lines)

        # 4b: Extract class names and register them
        class_names_before_dedup = extract_class_names(source)

        # 4c: For semanticQuery, remove hand-crafted classes and use imports instead
        if schema_info.name == "semanticQuery":
            source = remove_handcrafted_classes(source, schema_info)

        # 4d: Deduplicate against previously generated schemas
        source = deduplicate_against_registry(source, schema_info, registry, schemas)

        # 4e: Merge numbered variants (QueryExpressionContainer1-47 → single class)
        # This is now mostly redundant for semanticQuery since we remove variants,
        # but still useful for other schemas and as a fallback
        source = merge_numbered_variants(source)

        # 4f: Normalise non-None defaults on Optional (| None) fields.
        # datamodel-codegen copies JSON Schema defaults verbatim; for models
        # serialised with exclude_none=True this causes spurious output.
        source = _fix_optional_field_defaults(source)

        # 4f½: Replace constr() with Annotated[str, StringConstraints(...)].
        source = _replace_constr_with_annotated(source)

        # 4g: Apply any schema-specific field type corrections (e.g. class-name
        # collisions that the generic dedup step cannot resolve automatically).
        source = _apply_post_generation_fixes(source, schema_info)

        # 4h: Remove .model_rebuild() for classes not defined in this file
        source = _remove_stale_rebuild_calls(source)

        # 4i: Remove unused imports left by deduplication/merging
        source = _remove_unused_imports(source)

        # 4j: Write the post-processed source
        schema_info.output_file.write_text(source, encoding="utf-8")
        final_lines = source.count("\n")

        if final_lines < original_lines:
            reduction = (1 - final_lines / original_lines) * 100
            log.info(
                "  Post-processed: %d → %d lines (%.1f%% reduction)",
                original_lines,
                final_lines,
                reduction,
            )
        else:
            log.info("  Post-processed: %d lines (no duplicates found)", final_lines)

        if final_lines > MAX_LINES_WARN:
            log.warning(
                "  ⚠ File has %d lines (>%d) - may need manual review",
                final_lines,
                MAX_LINES_WARN,
            )

        # 4i: Register all classes from this schema (after dedup)
        final_classes = extract_class_names(source)
        final_signatures = extract_class_signatures(source)
        for cls_name in final_classes:
            registry.register(
                cls_name,
                schema_info.key,
                schema_info.import_path,
                signature=final_signatures.get(cls_name),
            )

        log.info("  Registered %d classes from %s", len(final_classes), schema_info.key)

        # 4j: Create __init__.py files
        create_init_files(schema_info)
        ensure_handcrafted_helper_files(schema_info)

        generated.append(schema_info)

    # Phase 5: Create top-level init
    log.info("")
    log.info("[Phase 5] Creating package __init__.py files...")
    create_top_level_init(generated)

    # Phase 6: Summary
    log.info("")
    log.info("=" * 70)
    log.info("SUMMARY")
    log.info("=" * 70)
    log.info("Generated : %d schemas", len(generated))
    log.info("Skipped   : %d schemas", len(skipped))
    log.info("Failed    : %d schemas", len(failed))
    log.info("Registry  : %d unique classes", len(registry.all_classes))
    log.info("")

    for s in generated:
        lines = s.output_file.read_text(encoding="utf-8").count("\n")
        status = "⚠" if lines > MAX_LINES_WARN else "✓"
        log.info("  %s %s v%s → %d lines", status, s.name, s.version, lines)

    for s in skipped:
        lines = s.output_file.read_text(encoding="utf-8").count("\n")
        log.info("  ~ %s v%s → %d lines (skipped)", s.name, s.version, lines)

    if failed:
        log.error("")
        log.error("FAILED SCHEMAS:")
        for s in failed:
            log.error("  ✗ %s v%s", s.name, s.version)

    log.info("")
    log.info("Output directory: %s", OUTPUT_ROOT)
    log.info("")

    return len(failed) == 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    """CLI entry point.  Parses arguments and delegates to :func:`generate_all`.

    Exit codes:
        0: all schemas generated successfully.
        1: one or more schemas failed, or ``--schema-root`` does not exist.
    """
    parser = argparse.ArgumentParser(
        description="Generate Pydantic V2 models from Power BI JSON schemas.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              python scripts/generate_models.py
              python scripts/generate_models.py --dry-run
              python scripts/generate_models.py --clean
              python scripts/generate_models.py --incremental
              python scripts/generate_models.py --schema-root /path/to/schemas
        """),
    )
    parser.add_argument(
        "--schema-root",
        type=Path,
        default=DEFAULT_SCHEMA_ROOT,
        help="Root directory containing the JSON schemas",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be generated without actually generating",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove existing generated files before regenerating",
    )
    parser.add_argument(
        "--incremental",
        action="store_true",
        help=(
            "Skip schemas whose model.py already exists. "
            "Existing schemas still populate the class registry so "
            "downstream deduplication works correctly."
        ),
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose/debug logging",
    )

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    if not args.schema_root.exists():
        log.error("Schema root not found: %s", args.schema_root)
        sys.exit(1)

    success = generate_all(
        schema_root=args.schema_root,
        targets=TARGET_SCHEMAS,
        dry_run=args.dry_run,
        clean=args.clean,
        incremental=args.incremental,
    )

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
