# generated by datamodel-codegen:
#   filename:  schema.json


from enum import Enum
from typing import Any

from pydantic import Field, RootModel

# --- Imports from dependency schemas (auto-generated) ---


class SemanticQuery(RootModel[Any]):
    root: Any = Field(
        ...,
        description="Defines shared definitions for queries and filters.",
        title="Semantic Query",
    )


class DataType(Enum):
    Binary = "Binary"
    Boolean = "Boolean"
    Date = "Date"
    DateTime = "DateTime"
    DateTimeZone = "DateTimeZone"
    Decimal = "Decimal"
    Double = "Double"
    Duration = "Duration"
    Integer = "Integer"
    Json = "Json"
    None_ = "None"
    Null = "Null"
    Text = "Text"
    Time = "Time"
    Variant = "Variant"


class TimeUnit(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5
    number_6 = 6
    number_7 = 7


class ArithmeticOperatorKind(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2
    number_3 = 3


class QueryComparisonKind(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4


class Type(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2


class QueryAggregateFunction(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5
    number_6 = 6
    number_7 = 7
    number_8 = 8
