# generated by datamodel-codegen:
#   filename:  schema.json


from enum import Enum
from typing import Any, Literal, Annotated

from pydantic import BaseModel, ConfigDict, Field, StringConstraints
from ...semanticquery.expressions import FilterDefinition, QueryExpressionContainer, QuerySortClause
from ...formattingobjectdefinitions.v1_3_0.model import HierarchyMatching
from ...semanticquery.v1_2_0.model import Type
from ...semanticquery.v1_3_0.model import SortDirection


class BookmarkOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applyOnlyToTargetVisuals: bool | None= Field(None,
        description='Only applies changes to selected visuals when the bookmark was captured.',
    )
    targetVisualNames: list[str] | None= Field(None, description='Specific visuals to which this bookmark applies.'
    )
    suppressActiveSection: bool | None= Field(None, description="Don't apply changes to active section."
    )
    suppressData: bool | None= Field(None, description="Don't apply data changes.")
    suppressDisplay: bool | None= Field(None, description="Don't apply display property changes."
    )


class HowCreated(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5
    number_6 = 6
    number_7 = 7


class JsonFilter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filterType: Any = Field(..., description='Type of json filter.')


class DataTable(Enum):
    accessible = 'accessible'
    normal = 'normal'


class MaximizedOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataTable: DataTable | None= Field(None, description='Type of table to show.')


class VisualContainerDisplayMode(Enum):
    maximize = 'maximize'
    spotlight = 'spotlight'
    elevation = 'elevation'
    hidden = 'hidden'


class VisualContainerGroupState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isHidden: bool | None= Field(None, description='Is the group hidden in the bookmark.'
    )
    children: dict[str, VisualContainerGroupState] | None= Field(None, description='State of child groups.'
    )


class DataViewWildcard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    matchingOption: Type = Field(..., description='Defines the matching option to use.')


class VisualContainerDisplayState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: VisualContainerDisplayMode = Field(
        ..., description='How is this visual shown in the bookmark.'
    )
    maximizedOptions: MaximizedOptions | None= Field(None, description='Options if maximized.'
    )


class Bookmark(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: Literal['https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.4.0/schema.json'] = Field(
        ..., alias='$schema', description='Defines the schema to use for an item.'
    )
    displayName: str = Field(..., description='Display name for the bookmark.')
    name: str = Field(
        ...,
        description='Unique identifier for the bookmark - unique across the report.',
    )
    options: BookmarkOptions | None= Field(None, description='Additional options for the bookmark'
    )
    explorationState: ExplorationState = Field(
        ..., description='Bookmark definition to use when applying this bookmark.'
    )


class ExplorationState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: str = Field(..., description='Version of bookmark.')
    activeSection: str = Field(
        ...,
        description='Name of the page that was active when this bookmark was captured.',
    )
    filters: FiltersState | None= Field(None,
        description='State of filters for the report when the bookmark was captured.',
    )
    sections: dict[str, SectionState] = Field(
        ..., description='State of all pages when the bookmark was captured.'
    )
    objects: DataViewObjectDefinitionUpdates | None= Field(None, description='Changes to formatting to apply in this bookmark.'
    )
    dataSourceVariables: str | None= Field(None,
        description='A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.',
    )


class FiltersState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    byName: dict[str, FilterContainerState] | None= Field(None, description='Filter containers that will be identified by name.'
    )
    byExpr: list[FilterContainerState] | None= Field(None, description='Filter containers that will be identified by expression.'
    )
    byType: list[FilterContainerState] | None= Field(None, description='Filter containers that will be identified by type.'
    )
    byTransientState: list[FilterContainerState] | None= Field(None, description='Filter containers that are transient'
    )


class FilterContainerState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    type: str | None= None
    filter: FilterDefinition | None= Field(None, description='Defines a filter element as a partial query structure'
    )
    expression: QueryExpressionContainer | None= Field(None,
        description='Holds a single expression and associated metadata.\nName, NativeReferenceName, and Annotations may be specified for any expression.\nEach other property represents a specific type of expression and exactly one of these other properties must be specified.',
    )
    restatement: str | None= None
    howCreated: HowCreated | None= None
    precedence: Literal[0] = Field(
        0,
        description='Precedence of the filter.  The higher the number, the higher the precedence of the filter.\n\nEach filter is evaluated in the presence of other filters which are strictly higher precedence,\nand in the absense of all filters which are equal or lower precedence.\n\nNote that not all precedence levels are encoded here yet.  For example, cross filters have higher\nprecedence than data filters, and data filters have higher precedence than drill filters.  Neither\ncross filters nor data filters have an entry in this enumeration yet, but instead have their\nprecedence enforced by explicit code in the FilterGenerator.  It is a future work item to encode\nall precendence levels here.\n\nNote also that when we add new precedence levels in this enumeration, we may have to change existing\nprecedence levels.  If that happens, we will need to add Upgrader code to translate the precedence\nlevels from one version to another.',
    )
    isTransient: bool | None= None
    cachedDisplayNames: list[FilterLabelIdPair] | None= None
    filterExpressionMetadata: FilterExpressionMetadata | DecomposedFilterExpressionMetadata | None= None


class FilterLabelIdPair(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: DataRepetitionSelector
    displayName: str


class DataRepetitionSelector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scopeId: QueryExpressionContainer | None= Field(None,
        description='Defines the intersection of scopes. For example - product color = red.',
    )
    wildcard: list[QueryExpressionContainer] | None= Field(None,
        description='Defines a match against all instances of a given DataView scope. Does not match Subtotals.\nDeprecated: - Use roles instead.',
    )
    roles: list[str] | None= Field(None, description='Matches against all fields in a role.'
    )
    total: list[QueryExpressionContainer] | None= Field(None, description='Matches against the totals and subtotals.')
    dataViewWildcard: DataViewWildcard | None= Field(None, description='Matches all instances or all totals or both.'
    )


class DataViewObjectDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: Selector | None= None
    properties: dict[str, Any]


class Selector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: list[DataRepetitionSelector] | None= Field(None, description='Scope is defined by data bound to the visual.'
    )
    metadata: str | None= Field(None, description='Defines the scope to a specific field.'
    )
    id: str | None= Field(None, description='User defined scope.')
    highlightMatching: Type | None= Field(None,
        description='Describes how the Selector should behave towards Highlighted Values within the Scope matched by that Selector.',
    )
    hierarchyMatching: HierarchyMatching | None= Field(None,
        description='Describes how the selector matches hierarchy values.\nThis also changes how the query is generated for {@link DataViewScopeWildcard} selectors.\nNow those selectors can produce scopedValues for the level those match.\n\nThere are two ways that we can match values in the hierarchy:\n1.',
    )
    order: float | None= Field(None,
        description='Specifies a user-defined ordering of identical properties.\nSelector constructors should strive to monitonically increase this number across identical properties differing by id.',
    )


class FilterExpressionMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expressions: list[QueryExpressionContainer] = Field(
        ...,
        description='Fields on which the filter is applied (which have group-on keys).',
    )
    cachedValueItems: list[IdentityValueMap] | None= Field(None,
        description='Defines the filter on the group-on key that is applied for the field.',
    )
    jsonFilter: JsonFilter | None= Field(None, description='Json filter metadata.')


class IdentityValueMap(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identities: list[DataRepetitionSelector]
    valueMap: dict[Annotated[str, StringConstraints(pattern=r'^[0-9]+$')], str]


class DecomposedFilterExpressionMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decomposedIdentities: DecomposedIdentities | None= Field(None,
        description='Defines the group-on key fields and the filters applied on them.',
    )
    expressions: list[Any] = Field(
        ...,
        description='Original fields (which have group-on keys) used in the filter.',
    )
    valueMap: list[dict[Annotated[str, StringConstraints(pattern=r'^[0-9]+$')], str]] | None = Field(None,
        description='Matches the index in decomposedIdentities with the queryRef for an expression.',
    )
    jsonFilter: JsonFilter | None= Field(None, description='Json filter metadata.')


class DecomposedIdentities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    values: list[
        list[
            dict[
                Annotated[str, StringConstraints(pattern=r'^[0-9]+$')],
                list[QueryExpressionContainer | QueryExpressionContainer], ] ]] = Field(
        ...,
        description="`values` have 3 levels\noutermost level:\n - for SelectorsByColumn[], it's the number of selectors in this array\n - for FilterExpressionMetadata, it's the number of cachedValueItems.\nsecond level:\n  - for SelectorsByColumn, it is the number of scopedIdentities in the particular SelectorsByColumn\n  - for FilterExpressionMetadata, it is the number of identities in a cachedValueItem\ninnermost level:\n  - the key is the index of the column structure of scopedIdentity in `columns` list;\n  - the the value is the expressions list in one identity",
    )
    columns: list[DecomposedTreeQueryExpressionContainer] = Field(
        ..., description='Defines the set of group-on key columns.'
    )


class DecomposedTreeQueryExpressionContainer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    left: DecomposedTreeQueryExpressionContainer | None= None
    right: DecomposedTreeQueryExpressionContainer | None= None
    value: QueryExpressionContainer | None= Field(None,
        description='Holds a single expression and associated metadata.\nName, NativeReferenceName, and Annotations may be specified for any expression.\nEach other property represents a specific type of expression and exactly one of these other properties must be specified.',
    )


class SectionState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filters: FiltersState | None= Field(None,
        description='State of filters for this page when the bookmark was captured.',
    )
    visualContainers: dict[str, VisualContainerState] = Field(
        ...,
        description='Flat list of visual-container-specific state.\nDoes not include state of groups.',
    )
    visualContainerGroups: dict[str, VisualContainerGroupState] | None= Field(None,
        description='Flat list of group-specific state.\nDoes not include state of visual containers.',
    )


class VisualContainerState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filters: FiltersState | None= Field(None,
        description='State of filters for this page when the bookmark was captured.',
    )
    singleVisual: SingleVisualConfigState | None= Field(None, description='State of the configuration of the visual.'
    )
    highlight: HighlightState | None= Field(None, description='Cross-highlights captured in the bookmark.'
    )


class SingleVisualConfigState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visualType: str | None= Field(None, description='Name of visual')
    autoSelectVisualType: bool | None= Field(None, description='Can the visual type change as data changes in the bookmark.'
    )
    targetType: str | None= Field(None,
        description='Change visual to this type - if different from the original state. Used by personalize this visual on the web.',
    )
    targetAutoSelectVisualType: bool | None= Field(None, description='Change auto changing visual type.'
    )
    objects: DataViewObjectDefinitionUpdates | None= Field(None, description='Changes to formatting to apply in this bookmark.'
    )
    orderBy: list[QuerySortClause] | None= Field(None, description='Updated ordering of data.'
    )
    activeProjections: (dict[ str, list[QueryExpressionContainer | QueryExpressionContainer],] | None) = Field(None, description='Updated projections that are used by the visual.')
    projections: (dict[ str, list[QueryExpressionContainer | QueryExpressionContainer],] | None) = Field(
        None,
        description='Projections are stored only when presentation changes are applied (such as during personalize visuals)\nor if the projections are resolved projections of a field parameter. When projections are resolved\nprojections of a field parameter but presentation changes are not applied, nulls will be present in the\narray to indicate where non-parameter projections of the visual are.',
    )
    parameters: dict[str, list[ParameterState]] | None= Field(None,
        description='Field parameters that were used as part of the query. We always capture parameter state when parameters\nare present regardless of the bookmark type.',
    )
    display: VisualContainerDisplayState | None= Field(None, description='Optional changes to how the visual is displayed.'
    )
    cachedFilterDisplayItems: list[FilterLabelIdPair] | None= None
    expansionStates: list[Any] | None= Field(None, description='Changes to expansion state.'
    )
    filterExpressionMetadata: FilterExpressionMetadata | DecomposedFilterExpressionMetadata | None= None
    isDrillDisabled: bool | None= Field(None, description='Indicates whether the drill feature is disabled'
    )


class DataViewObjectDefinitionUpdates(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    merge: dict[str, list[DataViewObjectDefinition]] | None= Field(None, description='ObjectDefinitions to be merged with the target.'
    )
    remove: list[DataViewObjectPropertyIdWithSelector] | None= Field(None, description='ObjectDefinitions to be deleted from the existing instances.'
    )


class DataViewObjectPropertyIdWithSelector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    object: str = Field(..., description='Name of visual object.')
    property: str = Field(
        ..., description='Name of property to change for the visual object.'
    )
    selector: Selector = Field(..., description='Scope at which to apply this change.')


class ParameterState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expr: QueryExpressionContainer = Field(..., description='Parameter expression.')
    index: float = Field(
        ..., description='Index from which parameter starts in the visual projection.'
    )
    length: float = Field(..., description='Number of fields created by the parameter.')
    sortDirection: SortDirection | None= Field(None,
        description="If the sort direction is set, the visual is sorted by this field parameter.\nThe implication of a visual being sorted by a field parameter is as follows during parameter resolution:\n- If none of the newly projected fields exist in the sort list, apply the parameter sort direction to the first projected field and add it to the end of the sort list.\n- If all the projected fields in the sort list have the opposite sort direction as the parameter's sort direction, flip the parameter's sort direction.",
    )


class HighlightState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selection: DecomposedSelectors | list[SelectorsByColumn]= Field(
        ..., description='Data points selected for the highlights.'
    )
    filterExpressionMetadata: FilterExpressionMetadata | DecomposedFilterExpressionMetadata | None= Field(None,
        description='Additional metadata for the filter generated from highlights.',
    )


class DecomposedSelectors(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decomposedIdentities: DecomposedIdentities | None= None
    queryNameMap: list[dict[Annotated[str, StringConstraints(pattern=r'^[0-9]+$')], list[float]]] | None = Field(None,
        description='The `queryNameIndex` key is the index in the queryNames array;\nthe `number` value is the columnIndex properties in DecomposedScopeIdentity.\nThis map tracks the different queryName and their column shapes present in each dataMap',
    )
    queryNames: list[str] | None= None
    metadata: list[list[str]] | None= None
    id: list[str] | None= None


class SelectorsByColumn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataMap: dict[str, list[DataRepetitionSelector]] | None= None
    metadata: list[str] | None= None
    id: str | None= None


VisualContainerGroupState.model_rebuild()
Bookmark.model_rebuild()
ExplorationState.model_rebuild()
FiltersState.model_rebuild()
FilterContainerState.model_rebuild()
FilterLabelIdPair.model_rebuild()
DataViewObjectDefinition.model_rebuild()
FilterExpressionMetadata.model_rebuild()
DecomposedFilterExpressionMetadata.model_rebuild()
DecomposedIdentities.model_rebuild()
DecomposedTreeQueryExpressionContainer.model_rebuild()
SectionState.model_rebuild()
VisualContainerState.model_rebuild()
SingleVisualConfigState.model_rebuild()
DataViewObjectDefinitionUpdates.model_rebuild()
HighlightState.model_rebuild()
