# generated by datamodel-codegen:
#   filename:  schema.json


from enum import Enum


# --- Imports from dependency schemas (auto-generated) ---

# --- Imports from dependency schemas (auto-generated) ---



class ApplyCalculationGroupTo(Enum):
    Sparkline = 'Sparkline'
    Point = 'Point'


class SortDirection(Enum):
    number_1 = 1
    number_2 = 2


