# generated by datamodel-codegen:
#   filename:  schema.json


from typing import Any

from pydantic import BaseModel, ConfigDict, Field

# --- Imports from dependency schemas (auto-generated) ---
from ...semanticquery.expressions import QueryExpressionContainer
from ...formattingobjectdefinitions.v1_3_0.model import (
    DataViewWildcard,
    HierarchyMatching,
    HighlightMatching,
)


class DataViewObjectDefinition(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    selector: Selector | None = None
    properties: dict[str, Any]


class Selector(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[DataRepetitionSelector] | None = Field(
        None, description="Scope is defined by data bound to the visual."
    )
    metadata: str | None = Field(
        None, description="Defines the scope to a specific field."
    )
    id: str | None = Field(None, description="User defined scope.")
    highlightMatching: HighlightMatching | None = Field(
        None,
        description="Describes how the Selector should behave towards Highlighted Values within the Scope matched by that Selector.",
    )
    hierarchyMatching: HierarchyMatching | None = Field(
        None,
        description="Describes how the selector matches hierarchy values.\nThis also changes how the query is generated for {@link DataViewScopeWildcard} selectors.\nNow those selectors can produce scopedValues for the level those match.\n\nThere are two ways that we can match values in the hierarchy:\n1.",
    )
    order: float | None = Field(
        None,
        description="Specifies a user-defined ordering of identical properties.\nSelector constructors should strive to monitonically increase this number across identical properties differing by id.",
    )


class DataRepetitionSelector(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scopeId: QueryExpressionContainer | None = Field(
        None,
        description="Defines the intersection of scopes. For example - product color = red.",
    )
    wildcard: list[QueryExpressionContainer] | None = Field(
        None,
        description="Defines a match against all instances of a given DataView scope. Does not match Subtotals.\nDeprecated: - Use roles instead.",
    )
    roles: list[str] | None = Field(
        None, description="Matches against all fields in a role."
    )
    total: list[QueryExpressionContainer] | None = Field(
        None, description="Matches against the totals and subtotals."
    )
    dataViewWildcard: DataViewWildcard | None = Field(
        None, description="Matches all instances or all totals or both."
    )


DataViewObjectDefinition.model_rebuild()
Selector.model_rebuild()
DataRepetitionSelector.model_rebuild()
